use sha2::{Digest, Sha256};

/// Information about a client request token, including its source and derivation.
#[derive(Debug, Clone, PartialEq)]
pub struct TokenInfo {
    pub value: String,
    pub source: TokenSource,
    pub operation_id: String,
}

/// Source of a client request token for traceability.
#[derive(Debug, Clone, PartialEq)]
pub enum TokenSource {
    /// Token was explicitly provided by the user via CLI
    UserProvided,
    /// Token was automatically generated when not provided
    AutoGenerated,
    /// Token was derived from another token for a specific operation step
    Derived {
        from: String, // Original token value
        step: String, // Step name (e.g., "create-changeset")
    },
}

impl TokenInfo {
    /// Create a new TokenInfo with user-provided token
    pub fn user_provided(value: String, operation_id: String) -> Self {
        Self {
            value,
            source: TokenSource::UserProvided,
            operation_id,
        }
    }

    /// Create a new TokenInfo with auto-generated token
    pub fn auto_generated(value: String, operation_id: String) -> Self {
        Self {
            value,
            source: TokenSource::AutoGenerated,
            operation_id,
        }
    }

    /// Derive a new token from this one for a specific operation step.
    ///
    /// Uses deterministic hashing to ensure the same primary token always
    /// generates the same derived tokens for retryability.
    pub fn derive_for_step(&self, step: &str) -> TokenInfo {
        let derived_value = derive_token(&self.value, step);

        TokenInfo {
            value: derived_value,
            source: TokenSource::Derived {
                from: self.value.clone(),
                step: step.to_string(),
            },
            operation_id: self.operation_id.clone(),
        }
    }

    /// Get the lineage of this token for debugging and tracing.
    ///
    /// Returns a vector of strings describing the token's derivation chain.
    pub fn trace_lineage(&self) -> Vec<String> {
        match &self.source {
            TokenSource::UserProvided => {
                vec![format!("User-provided token: {}", self.value)]
            }
            TokenSource::AutoGenerated => {
                vec![format!("Auto-generated token: {}", self.value)]
            }
            TokenSource::Derived { from, step } => {
                vec![
                    format!("Primary token: {}", from),
                    format!("Derived for step '{}': {}", step, self.value),
                ]
            }
        }
    }

    /// Check if this token was derived from another token
    pub fn is_derived(&self) -> bool {
        matches!(self.source, TokenSource::Derived { .. })
    }

    /// Get the root token value (either this token or the one it was derived from)
    pub fn root_token(&self) -> &str {
        match &self.source {
            TokenSource::Derived { from, .. } => from,
            _ => &self.value,
        }
    }
}

/// Derive a deterministic sub-token from a primary token and step name.
///
/// Uses SHA256 hashing to ensure the same inputs always produce the same output,
/// enabling safe retries of multi-step operations.
fn derive_token(primary_token: &str, step: &str) -> String {
    // Create deterministic hash of primary token + step
    let mut hasher = Sha256::new();
    hasher.update(primary_token.as_bytes());
    hasher.update(step.as_bytes());
    let hash_result = hasher.finalize();

    // Convert to hex and take first 8 characters
    let hash_hex = format!("{:x}", hash_result);
    let hash_short = &hash_hex[..8];

    // Take first 8 characters of original token
    let primary_short = if primary_token.len() >= 8 {
        &primary_token[..8]
    } else {
        primary_token
    };

    // Format as: primary_prefix-hash_suffix
    format!("{}-{}", primary_short, hash_short)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn token_info_user_provided() {
        let token = TokenInfo::user_provided("user-token-123".to_string(), "op-1".to_string());

        assert_eq!(token.value, "user-token-123");
        assert_eq!(token.operation_id, "op-1");
        assert!(matches!(token.source, TokenSource::UserProvided));
        assert!(!token.is_derived());
        assert_eq!(token.root_token(), "user-token-123");
    }

    #[test]
    fn token_info_auto_generated() {
        let token = TokenInfo::auto_generated("auto-token-456".to_string(), "op-2".to_string());

        assert_eq!(token.value, "auto-token-456");
        assert_eq!(token.operation_id, "op-2");
        assert!(matches!(token.source, TokenSource::AutoGenerated));
        assert!(!token.is_derived());
        assert_eq!(token.root_token(), "auto-token-456");
    }

    #[test]
    fn token_derivation_is_deterministic() {
        let primary = TokenInfo::user_provided(
            "abc123ef-4567-89ab-cdef-0123456789ab".to_string(),
            "op-1".to_string(),
        );

        // Derive the same token multiple times
        let derived1 = primary.derive_for_step("create-changeset");
        let derived2 = primary.derive_for_step("create-changeset");

        // Should be identical
        assert_eq!(derived1.value, derived2.value);
        assert_eq!(derived1.source, derived2.source);
        assert_eq!(derived1.operation_id, derived2.operation_id);
    }

    #[test]
    fn token_derivation_different_steps_produce_different_tokens() {
        let primary = TokenInfo::user_provided(
            "abc123ef-4567-89ab-cdef-0123456789ab".to_string(),
            "op-1".to_string(),
        );

        let create_token = primary.derive_for_step("create-changeset");
        let execute_token = primary.derive_for_step("execute-changeset");

        // Should be different values
        assert_ne!(create_token.value, execute_token.value);

        // But should both start with the primary token prefix
        assert!(create_token.value.starts_with("abc123ef"));
        assert!(execute_token.value.starts_with("abc123ef"));

        // And both should be derived from the same source
        if let TokenSource::Derived { from: from1, .. } = &create_token.source {
            if let TokenSource::Derived { from: from2, .. } = &execute_token.source {
                assert_eq!(from1, from2);
                assert_eq!(from1, &primary.value);
            } else {
                panic!("Execute token should be derived");
            }
        } else {
            panic!("Create token should be derived");
        }
    }

    #[test]
    fn derived_token_properties() {
        let primary =
            TokenInfo::user_provided("test-primary-token".to_string(), "op-1".to_string());
        let derived = primary.derive_for_step("test-step");

        assert!(derived.is_derived());
        assert_eq!(derived.root_token(), "test-primary-token");
        assert_eq!(derived.operation_id, "op-1"); // Should inherit operation ID

        if let TokenSource::Derived { from, step } = &derived.source {
            assert_eq!(from, "test-primary-token");
            assert_eq!(step, "test-step");
        } else {
            panic!("Token should be derived");
        }
    }

    #[test]
    fn token_trace_lineage() {
        // Test user-provided token lineage
        let user_token = TokenInfo::user_provided("user-token".to_string(), "op-1".to_string());
        let user_lineage = user_token.trace_lineage();
        assert_eq!(user_lineage.len(), 1);
        assert!(user_lineage[0].contains("User-provided token: user-token"));

        // Test auto-generated token lineage
        let auto_token = TokenInfo::auto_generated("auto-token".to_string(), "op-2".to_string());
        let auto_lineage = auto_token.trace_lineage();
        assert_eq!(auto_lineage.len(), 1);
        assert!(auto_lineage[0].contains("Auto-generated token: auto-token"));

        // Test derived token lineage
        let primary = TokenInfo::user_provided("primary-token".to_string(), "op-3".to_string());
        let derived = primary.derive_for_step("test-step");
        let derived_lineage = derived.trace_lineage();
        assert_eq!(derived_lineage.len(), 2);
        assert!(derived_lineage[0].contains("Primary token: primary-token"));
        assert!(derived_lineage[1].contains("Derived for step 'test-step'"));
    }

    #[test]
    fn derive_token_function_is_deterministic() {
        let primary = "test-token-123";
        let step = "create-changeset";

        let result1 = derive_token(primary, step);
        let result2 = derive_token(primary, step);

        assert_eq!(result1, result2);
    }

    #[test]
    fn derive_token_format() {
        let primary = "abc123ef-4567-89ab-cdef-0123456789ab";
        let step = "create-changeset";

        let result = derive_token(primary, step);

        // Should start with first 8 chars of primary
        assert!(result.starts_with("abc123ef-"));

        // Should have format: prefix-hash
        let parts: Vec<&str> = result.split('-').collect();
        assert_eq!(parts.len(), 2);
        assert_eq!(parts[0], "abc123ef");
        assert_eq!(parts[1].len(), 8); // Hash should be 8 hex characters

        // Hash part should be valid hex
        assert!(parts[1].chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn derive_token_with_short_primary() {
        let primary = "short";
        let step = "test";

        let result = derive_token(primary, step);

        // Should start with the full primary token since it's less than 8 chars
        assert!(result.starts_with("short-"));

        let parts: Vec<&str> = result.split('-').collect();
        assert_eq!(parts[0], "short");
        assert_eq!(parts[1].len(), 8);
    }

    #[test]
    fn derive_token_different_inputs_produce_different_outputs() {
        let token1 = derive_token("token1", "step1");
        let token2 = derive_token("token1", "step2");
        let token3 = derive_token("token2", "step1");

        // All should be different
        assert_ne!(token1, token2);
        assert_ne!(token1, token3);
        assert_ne!(token2, token3);
    }
}
