//! Layer 3 End-to-End Tests: DynamicOutputManager with Mode Switching
//!
//! This test suite validates the complete DynamicOutputManager functionality
//! including event buffering, mode switching, event replay, and end-to-end
//! scenarios that simulate real CloudFormation operations.

use chrono::Utc;
use iidy::output::data::*;
use iidy::output::fixtures::FixtureLoader;
use iidy::output::manager::{DynamicOutputManager, OutputOptions};
use iidy::output::renderer::OutputMode;
use std::collections::HashMap;
use tokio;

/// Helper function to create test output options
fn create_test_output_options() -> OutputOptions {
    use iidy::cli::{AwsOpts, Cli, ColorChoice, Commands, DescribeArgs, GlobalOpts, Theme};
    let cli = Cli {
        global_opts: GlobalOpts {
            environment: "test".to_string(),
            color: ColorChoice::Auto,
            theme: Theme::Auto,
            output_mode: None,
            debug: false,
            log_full_error: false,
        },
        aws_opts: AwsOpts {
            region: None,
            profile: None,
            assume_role_arn: None,
            client_request_token: None,
        },
        command: Commands::DescribeStack(DescribeArgs {
            stackname: "test-stack".to_string(),
            events: 50,
            query: None,
        }),
    };
    OutputOptions::new(cli)
}

/// Helper function to create sample command metadata
fn create_sample_command_metadata() -> CommandMetadata {
    CommandMetadata {
        iidy_environment: "test".to_string(),
        region: "us-east-1".to_string(),
        profile: Some("test-profile".to_string()),
        cli_arguments: [
            ("argsfile".to_string(), "stack-args.yaml".to_string()),
            ("template".to_string(), "template.yaml".to_string()),
        ]
        .into_iter()
        .collect(),
        iam_service_role: None,
        current_iam_principal: "arn:aws:iam::123456789012:user/test-user".to_string(),
        credential_source: "profile 'test-profile' (default)".to_string(),
        iidy_version: "2.0.0".to_string(),
        primary_token: TokenInfo {
            value: "test-token-001".to_string(),
            source: TokenSource::AutoGenerated,
            operation_id: "create-stack-001".to_string(),
        },
        derived_tokens: vec![],
    }
}

/// Helper function to create sample status update
fn create_sample_status_update(message: &str, level: StatusLevel) -> StatusUpdate {
    StatusUpdate {
        message: message.to_string(),
        timestamp: Utc::now(),
        level,
    }
}

#[tokio::test]
async fn test_dynamic_output_manager_creation_and_initialization() {
    // Test creation with Plain mode
    let options = create_test_output_options();
    let manager = DynamicOutputManager::new(OutputMode::Plain, options.clone())
        .await
        .expect("Should create DynamicOutputManager with Plain mode");

    drop(manager);

    // Test creation with Interactive mode
    let manager = DynamicOutputManager::new(OutputMode::Interactive, options.clone())
        .await
        .expect("Should create DynamicOutputManager with Interactive mode");
    drop(manager);

    // Test creation with JSON mode
    let manager = DynamicOutputManager::new(OutputMode::Json, options)
        .await
        .expect("Should create DynamicOutputManager with JSON mode");
    drop(manager);
}

#[tokio::test]
async fn test_basic_rendering_and_buffering() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options)
        .await
        .expect("Should create manager");

    // Render some data
    let metadata = create_sample_command_metadata();
    manager
        .render(OutputData::CommandMetadata(metadata))
        .await
        .expect("Should render command metadata");

    // Render a status update
    let status = create_sample_status_update("Operation starting", StatusLevel::Info);
    manager
        .render(OutputData::StatusUpdate(status))
        .await
        .expect("Should render status update");
}

#[tokio::test]
async fn test_all_output_data_types_rendering() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Interactive, options)
        .await
        .expect("Should create manager");

    // Test CommandMetadata
    let metadata = create_sample_command_metadata();
    manager
        .render(OutputData::CommandMetadata(metadata))
        .await
        .expect("Should render CommandMetadata");

    // Test StackDefinition
    let stack_def = StackDefinition {
        name: "test-stack".to_string(),
        stackset_name: None,
        description: Some("Test stack".to_string()),
        status: "CREATE_COMPLETE".to_string(),
        status_reason: None,
        capabilities: vec!["CAPABILITY_IAM".to_string()],
        service_role: None,
        tags: HashMap::new(),
        parameters: HashMap::new(),
        disable_rollback: false,
        termination_protection: false,
        creation_time: Some(Utc::now()),
        last_updated_time: None,
        timeout_in_minutes: Some(30),
        notification_arns: vec![],
        stack_policy: None,
        arn: "arn:aws:cloudformation:us-east-1:123456789012:stack/test-stack/id".to_string(),
        console_url: "https://console.aws.amazon.com/cloudformation".to_string(),
        region: "us-east-1".to_string(),
    };
    manager
        .render(OutputData::StackDefinition(stack_def, true))
        .await
        .expect("Should render StackDefinition");

    // Test StatusUpdate
    let status = create_sample_status_update("Test status", StatusLevel::Info);
    manager
        .render(OutputData::StatusUpdate(status))
        .await
        .expect("Should render StatusUpdate");

    // Test CommandResult
    let result = CommandResult {
        success: true,
        elapsed_seconds: 120,
        message: Some("Operation completed".to_string()),
        exit_code: 0,
    };
    manager
        .render(OutputData::CommandResult(result))
        .await
        .expect("Should render CommandResult");

    let error = ErrorInfo {
        error_type: "TestError".to_string(),
        message: "Test error message".to_string(),
        timestamp: Utc::now(),
        suggestions: vec!["Try again".to_string()],
        error_details: ErrorDetails::Generic(Some("Error details".to_string())),
    };
    manager
        .render(OutputData::Error(error))
        .await
        .expect("Should render ErrorInfo");
}

#[tokio::test]
async fn test_end_to_end_cloudformation_operation_simulation() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options)
        .await
        .expect("Should create manager");

    // Simulate a complete CloudFormation create-stack operation

    // 1. Command Metadata
    let metadata = create_sample_command_metadata();
    manager
        .render(OutputData::CommandMetadata(metadata))
        .await
        .expect("Should render command metadata");

    // 2. Stack Definition
    let stack_def = StackDefinition {
        name: "test-infrastructure".to_string(),
        stackset_name: None,
        description: Some("Test infrastructure stack".to_string()),
        status: "CREATE_IN_PROGRESS".to_string(),
        status_reason: None,
        capabilities: vec!["CAPABILITY_IAM".to_string()],
        service_role: None,
        tags: [("Environment".to_string(), "test".to_string())]
            .into_iter()
            .collect(),
        parameters: [("InstanceType".to_string(), "t3.micro".to_string())]
            .into_iter()
            .collect(),
        disable_rollback: false,
        termination_protection: false,
        creation_time: Some(Utc::now()),
        last_updated_time: None,
        timeout_in_minutes: Some(30),
        notification_arns: vec![],
        stack_policy: None,
        arn: "arn:aws:cloudformation:us-east-1:123456789012:stack/test-infrastructure/id"
            .to_string(),
        console_url: "https://console.aws.amazon.com/cloudformation".to_string(),
        region: "us-east-1".to_string(),
    };
    manager
        .render(OutputData::StackDefinition(stack_def, true))
        .await
        .expect("Should render stack definition");

    // 3. Status Updates during operation
    let progress_updates = vec![
        ("Starting stack creation", StatusLevel::Info),
        ("Creating VPC", StatusLevel::Info),
        ("VPC created successfully", StatusLevel::Success),
        ("Creating security group", StatusLevel::Info),
        ("Security group created", StatusLevel::Success),
        ("Creating EC2 instance", StatusLevel::Info),
        ("EC2 instance created", StatusLevel::Success),
    ];

    for (message, level) in progress_updates {
        let status = create_sample_status_update(message, level);
        manager
            .render(OutputData::StatusUpdate(status))
            .await
            .expect("Should render status update");
    }

    // 4. Command Result
    let result = CommandResult {
        success: true,
        elapsed_seconds: 347,
        message: Some("Stack 'test-infrastructure' created successfully".to_string()),
        exit_code: 0,
    };
    manager
        .render(OutputData::CommandResult(result))
        .await
        .expect("Should render command result");
}

#[tokio::test]
async fn test_integration_with_fixture_data() {
    // Load real fixture data and test with DynamicOutputManager
    let loader = FixtureLoader::new();
    let fixture = loader
        .load_test_fixture("create-stack-happy-path")
        .expect("Should load test fixture");

    let output_data = loader
        .fixture_to_output_data(&fixture)
        .expect("Should convert fixture to OutputData");

    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Interactive, options)
        .await
        .expect("Should create manager");

    // Render all fixture data
    for data in &output_data {
        manager
            .render(data.clone())
            .await
            .expect("Should render fixture data");
    }
}

#[tokio::test]
async fn test_error_handling_during_rendering() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options)
        .await
        .expect("Should create manager");

    let error_info = ErrorInfo {
        error_type: "ValidationError".to_string(),
        message: "Stack parameter validation failed".to_string(),
        timestamp: Utc::now(),
        suggestions: vec![
            "Check parameter values in stack-args.yaml".to_string(),
            "Verify instance types are available in your region".to_string(),
        ],
        error_details: ErrorDetails::Generic(Some(
            "Parameter 'InstanceType' has invalid value".to_string(),
        )),
    };

    manager
        .render(OutputData::Error(error_info))
        .await
        .expect("Should render error information");
}
