use crate::{
    timing::{TokenInfo, TokenSource},
    cfn::CfnContext,
};

/// Console reporter for CloudFormation operations with token visibility.
/// 
/// This struct provides formatted console output for token usage, operation progress,
/// and summaries. Token information is always displayed to provide transparency
/// about idempotency tokens being used for CloudFormation operations.
pub struct ConsoleReporter {
    operation_name: String,
}

impl ConsoleReporter {
    /// Create a new console reporter for the given operation.
    /// 
    /// # Arguments
    /// * `operation_name` - Name of the operation (e.g., "create-stack", "update-stack --changeset")
    pub fn new(operation_name: &str) -> Self {
        Self {
            operation_name: operation_name.to_string(),
        }
    }
    
    /// Display information about the primary token being used.
    /// 
    /// Shows different messages based on the token source (user-provided vs auto-generated)
    /// to help users understand the idempotency behavior.
    pub fn show_primary_token(&self, token: &TokenInfo) {
        
        match &token.source {
            TokenSource::UserProvided => {
                println!("🔑 Using provided idempotency token: {}", token.value);
            },
            TokenSource::AutoGenerated => {
                println!("🎲 Generated idempotency token: {} (save this for retries)", token.value);
            },
            TokenSource::Derived { from, step } => {
                println!("🔗 Using derived token: {} (from {} for step {})", 
                    token.value, &from[..8.min(from.len())], step);
            },
        }
    }
    
    /// Display information about a token being used for a specific operation step.
    /// 
    /// This is typically called before each AWS API call in multi-step operations
    /// to show which derived token is being used.
    /// 
    /// # Arguments
    /// * `step` - The operation step name
    /// * `token` - The token being used for this step
    pub fn show_step_token(&self, step: &str, token: &TokenInfo) {
        
        match &token.source {
            TokenSource::Derived { from, .. } => {
                let from_short = &from[..8.min(from.len())];
                println!("   🔄 Step '{}' token: {} (derived from {})", 
                    step, token.value, from_short);
            },
            _ => {
                println!("   🔄 Step '{}' token: {}", step, token.value);
            },
        }
    }
    
    /// Display a summary of all tokens used during the operation.
    /// 
    /// This is typically called at the end of an operation to provide a complete
    /// audit trail of token usage for debugging and compliance purposes.
    /// 
    /// # Arguments
    /// * `context` - The CfnContext containing token usage history
    pub fn show_operation_summary(&self, context: &CfnContext) {
        
        let used_tokens = context.get_used_tokens();
        if used_tokens.is_empty() {
            return;
        }
        
        println!();
        println!("📋 Token Summary for {}:", self.operation_name);
        
        // Show primary token first
        let primary = context.primary_token();
        match &primary.source {
            TokenSource::UserProvided => {
                println!("   Primary: {} (user-provided)", primary.value);
            },
            TokenSource::AutoGenerated => {
                println!("   Primary: {} (auto-generated)", primary.value);
            },
            _ => {
                println!("   Primary: {}", primary.value);
            },
        }
        
        // Show derived tokens
        for token in &used_tokens {
            if let TokenSource::Derived { step, .. } = &token.source {
                println!("   Step '{}': {}", step, token.value);
            }
        }
        
        // Show operation correlation info
        println!("   Operation ID: {}", primary.operation_id);
    }
    
    /// Display a progress message for the current operation.
    /// 
    /// This provides consistent formatting for operation progress messages.
    /// 
    /// # Arguments
    /// * `message` - The progress message to display
    pub fn show_progress(&self, message: &str) {
        println!("🔄 {}", message);
    }
    
    /// Display a success message for the current operation.
    /// 
    /// # Arguments
    /// * `message` - The success message to display
    pub fn show_success(&self, message: &str) {
        println!("✅ {}", message);
    }
    
    /// Display an error message for the current operation.
    /// 
    /// # Arguments
    /// * `message` - The error message to display
    pub fn show_error(&self, message: &str) {
        eprintln!("❌ {}", message);
    }
    
    /// Display a warning message for the current operation.
    /// 
    /// # Arguments
    /// * `message` - The warning message to display
    pub fn show_warning(&self, message: &str) {
        println!("⚠️  {}", message);
    }
    
    /// Display operation timing information.
    /// 
    /// # Arguments
    /// * `elapsed_seconds` - Number of seconds elapsed
    pub fn show_elapsed_time(&self, elapsed_seconds: i64) {
        if elapsed_seconds > 0 {
            println!("⏱  {} seconds elapsed...", elapsed_seconds);
        }
    }
    
    /// Display final operation completion with timing.
    /// 
    /// # Arguments
    /// * `total_seconds` - Total operation duration in seconds
    pub fn show_completion(&self, total_seconds: i64) {
        println!("✅ {} completed in {} seconds", self.operation_name, total_seconds);
    }
    
    
    /// Get the operation name.
    pub fn operation_name(&self) -> &str {
        &self.operation_name
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::timing::{MockTimeProvider, TokenInfo};
    use std::sync::Arc;
    
    #[test]
    fn console_reporter_creation() {
        let reporter = ConsoleReporter::new("test-operation");
        assert_eq!(reporter.operation_name(), "test-operation");
    }
    
    #[test]
    fn show_primary_token_user_provided() {
        let reporter = ConsoleReporter::new("test-op");
        let token = TokenInfo::user_provided("user-token-123".to_string(), "op-1".to_string());
        
        // We can't easily capture stdout in unit tests, but we can verify the method doesn't panic
        reporter.show_primary_token(&token);
    }
    
    #[test]
    fn show_primary_token_auto_generated() {
        let reporter = ConsoleReporter::new("test-op");
        let token = TokenInfo::auto_generated("auto-token-456".to_string(), "op-2".to_string());
        
        reporter.show_primary_token(&token);
    }
    
    #[test]
    fn show_primary_token_derived() {
        let reporter = ConsoleReporter::new("test-op");
        let primary = TokenInfo::user_provided("primary-token".to_string(), "op-3".to_string());
        let derived = primary.derive_for_step("test-step");
        
        reporter.show_primary_token(&derived);
    }
    
    #[test]
    fn show_step_token_derived() {
        let reporter = ConsoleReporter::new("test-op");
        let primary = TokenInfo::user_provided("primary-token-123".to_string(), "op-1".to_string());
        let derived = primary.derive_for_step("create-changeset");
        
        reporter.show_step_token("create-changeset", &derived);
    }
    
    #[test]
    fn show_step_token_primary() {
        let reporter = ConsoleReporter::new("test-op");
        let token = TokenInfo::user_provided("primary-token-123".to_string(), "op-1".to_string());
        
        reporter.show_step_token("single-step", &token);
    }
    
    
    #[test]
    fn progress_and_status_messages() {
        let reporter = ConsoleReporter::new("test-operation");
        
        // These should not panic and should format correctly
        reporter.show_progress("Creating stack...");
        reporter.show_success("Stack created successfully");
        reporter.show_error("Stack creation failed");
        reporter.show_warning("Stack policy not found");
        reporter.show_elapsed_time(45);
        reporter.show_completion(120);
    }
    
    #[test]
    fn show_operation_summary_with_derived_tokens() {
        use crate::cfn::CfnContext;
        use aws_sdk_cloudformation::Client;
        
        let fixed_time = chrono::Utc::now();
        let time_provider = Arc::new(MockTimeProvider::new(fixed_time));
        let config = aws_config::SdkConfig::builder()
            .region(aws_types::region::Region::new("us-east-1"))
            .behavior_version(aws_config::BehaviorVersion::latest())
            .build();
        let client = Client::new(&config);
        let token_info = TokenInfo::user_provided("primary-token-123".to_string(), "test-op-1".to_string());
        
        let context = CfnContext::new_without_start_time(client, time_provider, token_info);
        
        // Derive some tokens
        let _create_token = context.derive_token_for_step("create-changeset");
        let _execute_token = context.derive_token_for_step("execute-changeset");
        
        let reporter = ConsoleReporter::new("update-stack --changeset");
        reporter.show_operation_summary(&context);
        
        // Verify context has the expected tokens
        let used_tokens = context.get_used_tokens();
        assert_eq!(used_tokens.len(), 3); // Primary + 2 derived
    }
    
    
    #[test]
    fn token_truncation_for_display() {
        let reporter = ConsoleReporter::new("test-op");
        let long_token = "very-long-primary-token-that-exceeds-eight-characters";
        let primary = TokenInfo::user_provided(long_token.to_string(), "op-1".to_string());
        let derived = primary.derive_for_step("test-step");
        
        // Should handle long tokens gracefully (we can't easily test the output,
        // but we can verify it doesn't panic)
        reporter.show_step_token("test-step", &derived);
    }
}