use anyhow::{Result, anyhow};

use crate::cfn::{create_context_for_operation, stack_operations::collect_stack_contents};
use crate::cli::{Cli, ToArgMap, DescribeArgs};
use crate::output::{
    DynamicOutputManager, OutputData, convert_stack_to_definition,
    manager::OutputOptions,
    CommandMetadata, TokenInfo, TokenSource,
    aws_conversion::{convert_stack_events_to_display_with_max, convert_aws_error_to_error_info}
};

// Note: Stack formatting logic has been moved to the output renderers
// where it can be applied consistently across all modes (Interactive, Plain, JSON).

/// Retrieve a stack description from AWS and display it.
///
/// Uses the data-driven output architecture for consistent rendering across output modes.
/// The stack details can be displayed in Interactive (with colors and formatting), 
/// Plain (CI-friendly), or JSON (machine-readable) formats.
/// 
/// Returns exit code (0 for success, 1 for failure).
pub async fn describe_stack(cli: &Cli, args: &DescribeArgs) -> Result<i32> {
    let opts = cli.aws_opts.clone().normalize();

    // Setup data-driven output manager FIRST to show immediate UI feedback
    let output_options = OutputOptions::new(cli.clone());
    let mut output_manager = DynamicOutputManager::new(
        cli.global_opts.effective_output_mode(),
        output_options
    ).await?;

    let event_count = args.events as usize;
    
    // Start parallel rendering and show first section immediately
    let sender = output_manager.start();
    
    // Tell the renderer what operation we're doing so it shows the first section heading
    let metadata = CommandMetadata {
        iidy_environment: cli.global_opts.environment.clone(),
        region: opts.region.clone().unwrap_or_default(),
        profile: opts.profile.clone(),
        cli_arguments: {
            let mut cli_args = opts.to_arg_map();
            cli_args.extend(args.to_arg_map());
            cli_args
        },
        iam_service_role: None,
        current_iam_principal: "".to_string(), // Would need to query AWS STS
        iidy_version: env!("CARGO_PKG_VERSION").to_string(),
        primary_token: TokenInfo {
            value: "".to_string(),
            source: TokenSource::AutoGenerated,
            operation_id: args.stackname.clone(),
        },
        derived_tokens: Vec::new(),
    };
    let _ = sender.send(OutputData::CommandMetadata(metadata));

    // Now setup AWS context (fast - automatically uses system time for read-only operations)
    let operation = cli.command.to_cfn_operation();
    let context = create_context_for_operation(&opts, operation).await?;
    
    // Clone values needed for the async tasks
    let client = context.client.clone();
    let stack_name = args.stackname.clone();
    
    // Start all three async operations in parallel
    let stack_task = {
        let client = client.clone();
        let stack_name = stack_name.clone();
        let tx = sender.clone();
        tokio::spawn(async move {
            let stack_resp = client
                .describe_stacks()
                .stack_name(&stack_name)
                .send()
                .await
                .map_err(anyhow::Error::from)?;
                
            let stack = stack_resp
                .stacks
                .and_then(|mut s| s.pop())
                .ok_or_else(|| anyhow!("stack not found"))?;
                
            let output_data = convert_stack_to_definition(&stack, true);
            let _ = tx.send(output_data);
            Ok::<(), anyhow::Error>(())
        })
    };
    
    let events_task = {
        let client = client.clone();
        let stack_name = stack_name.clone();
        let tx = sender.clone();
        tokio::spawn(async move {
            let first_events_resp = client
                .describe_stack_events()
                .stack_name(&stack_name)
                .send()
                .await
                .map_err(anyhow::Error::from)?;
        
            // Continue fetching stack events if needed (pagination)
            let mut all_events = first_events_resp.stack_events.unwrap_or_default();
            let mut next_token = first_events_resp.next_token;
            
            // Fetch additional pages if needed
            while next_token.is_some() && all_events.len() < event_count * 2 {
                let events_resp = client
                    .describe_stack_events()
                    .stack_name(&stack_name)
                    .set_next_token(next_token)
                    .send()
                    .await?;
                    
                let mut page_events = events_resp.stack_events.unwrap_or_default();
                all_events.append(&mut page_events);
                next_token = events_resp.next_token;
            }
            
            // Create events display
            let output_data = convert_stack_events_to_display_with_max(
                all_events,
                &format!("Previous Stack Events (max {}):", event_count),
                Some(event_count),
            );
            
            let _ = tx.send(output_data);
            Ok::<(), anyhow::Error>(())
        })
    };
    
    let contents_task = {
        let context = context.clone();
        let stack_name = stack_name.clone();
        let tx = sender.clone();
        tokio::spawn(async move {
            let stack_contents = collect_stack_contents(&context, &stack_name).await?;
            let _ = tx.send(OutputData::StackContents(stack_contents));
            Ok::<(), anyhow::Error>(())
        })
    };
    
    // Drop the original sender so the receiver knows when all tasks are done
    drop(sender);
    
    // Process and render all data from parallel operations
    output_manager.stop().await?;
    
    // Wait for all tasks to complete and handle any errors
    let (stack_result, events_result, contents_result) = tokio::join!(
        stack_task,
        events_task, 
        contents_task
    );
    
    // Helper to handle task results consistently
    let handle_task_result = |result: Result<Result<(), anyhow::Error>, tokio::task::JoinError>| -> Option<anyhow::Error> {
        match result {
            Err(join_error) => Some(join_error.into()),
            Ok(Err(task_error)) => Some(task_error),
            Ok(Ok(())) => None,
        }
    };
    
    // Check all task results and show first error encountered
    for task_result in [stack_result, events_result, contents_result] {
        if let Some(error) = handle_task_result(task_result) {
            let error_info = convert_aws_error_to_error_info(&error);
            output_manager.render(OutputData::Error(error_info)).await?;
            return Ok(1); // Return exit code 1 for failure
        }
    }

    Ok(0) // Return exit code 0 for success
}

#[cfg(test)]
mod tests {
    // Tests for this module are now primarily in the output conversion utilities
    // and renderer integration tests. The describe_stack function is tested end-to-end
    // through the data-driven output architecture.
}
