use anyhow::{Result, anyhow};

use crate::{
    cfn::create_context_for_operation,
    cli::{Cli, ToArgMap, Commands},
    output::{
        DynamicOutputManager, OutputData, convert_stack_to_definition,
        StackContents, StackStatusInfo, CfnOperation,
    },
};

// Note: Stack formatting logic has been moved to the output renderers
// where it can be applied consistently across all modes (Interactive, Plain, JSON).

/// Retrieve a stack description from AWS and display it.
///
/// Uses the data-driven output architecture for consistent rendering across output modes.
/// The stack details can be displayed in Interactive (with colors and formatting), 
/// Plain (CI-friendly), or JSON (machine-readable) formats.
pub async fn describe_stack(cli: &Cli) -> Result<()> {
    let Commands::DescribeStack(args) = &cli.command else {
        return Err(anyhow::anyhow!("Invalid command for describe_stack"));
    };
    
    // Normalize AWS options 
    let opts = cli.aws_opts.clone().normalize();

    // Setup data-driven output manager FIRST to show immediate UI feedback
    let output_options = crate::output::manager::OutputOptions::new(cli.clone());
    let mut output_manager = DynamicOutputManager::new(
        cli.global_opts.effective_output_mode(),
        output_options
    ).await?;

    let event_count = args.events as usize;
    
    // Start parallel rendering and show first section immediately
    let sender = output_manager.start();
    
    // Tell the renderer what operation we're doing so it shows the first section heading
    let metadata = crate::output::CommandMetadata {
        iidy_environment: cli.global_opts.environment.clone(),
        region: opts.region.clone().unwrap_or_default(),
        profile: opts.profile.clone(),
        cli_arguments: {
            let mut cli_args = opts.to_arg_map();
            cli_args.extend(args.to_arg_map());
            cli_args
        },
        iam_service_role: None,
        current_iam_principal: "".to_string(), // Would need to query AWS STS
        iidy_version: env!("CARGO_PKG_VERSION").to_string(),
        primary_token: crate::output::TokenInfo {
            value: "".to_string(),
            source: crate::output::TokenSource::AutoGenerated,
            operation_id: args.stackname.clone(),
        },
        derived_tokens: Vec::new(),
    };
    let _ = sender.send(OutputData::CommandMetadata(metadata));

    // Now setup AWS context (fast - automatically uses system time for read-only operations)
    let context = create_context_for_operation(&opts, CfnOperation::DescribeStack).await?;
    
    // Clone values needed for the async tasks
    let client = context.client.clone();
    let stack_name = args.stackname.clone();
    
    // Start all three async operations in parallel
    let stack_task = {
        let client = client.clone();
        let stack_name = stack_name.clone();
        let tx = sender.clone();
        tokio::spawn(async move {
            let stack_resp = client
                .describe_stacks()
                .stack_name(&stack_name)
                .send()
                .await
                .map_err(anyhow::Error::from)?;
                
            let stack = stack_resp
                .stacks
                .and_then(|mut s| s.pop())
                .ok_or_else(|| anyhow!("stack not found"))?;
                
            let output_data = convert_stack_to_definition(&stack, true);
            let _ = tx.send(output_data);
            Ok::<(), anyhow::Error>(())
        })
    };
    
    let events_task = {
        let client = client.clone();
        let stack_name = stack_name.clone();
        let tx = sender.clone();
        tokio::spawn(async move {
            let first_events_resp = client
                .describe_stack_events()
                .stack_name(&stack_name)
                .send()
                .await
                .map_err(anyhow::Error::from)?;
        
            // Continue fetching stack events if needed (pagination)
            let mut all_events = first_events_resp.stack_events.unwrap_or_default();
            let mut next_token = first_events_resp.next_token;
            
            // Fetch additional pages if needed
            while next_token.is_some() && all_events.len() < event_count * 2 {
                let events_resp = client
                    .describe_stack_events()
                    .stack_name(&stack_name)
                    .set_next_token(next_token)
                    .send()
                    .await?;
                    
                let mut page_events = events_resp.stack_events.unwrap_or_default();
                all_events.append(&mut page_events);
                next_token = events_resp.next_token;
            }
            
            // Create events display
            let output_data = crate::output::aws_conversion::convert_stack_events_to_display_with_max(
                all_events,
                &format!("Previous Stack Events (max {}):", event_count),
                Some(event_count),
            );
            
            let _ = tx.send(output_data);
            Ok::<(), anyhow::Error>(())
        })
    };
    
    let contents_task = {
        let client = client.clone();
        let stack_name = stack_name.clone();
        let tx = sender.clone();
        tokio::spawn(async move {
            // Get both stack info and resources in parallel
            let (stack_resp, resources_resp) = tokio::try_join!(
                async {
                    client
                        .describe_stacks()
                        .stack_name(&stack_name)
                        .send()
                        .await
                        .map_err(anyhow::Error::from)
                },
                async {
                    client
                        .describe_stack_resources()
                        .stack_name(&stack_name)
                        .send()
                        .await
                        .map_err(anyhow::Error::from)
                }
            )?;
                
            let stack = stack_resp
                .stacks
                .and_then(|mut s| s.pop())
                .ok_or_else(|| anyhow!("stack not found"))?;
        
            let resources = crate::output::aws_conversion::convert_stack_resources(
                resources_resp.stack_resources.unwrap_or_default()
            );

            // Extract outputs from stack
            let outputs = crate::output::aws_conversion::convert_stack_outputs(
                stack.outputs.unwrap_or_default()
            );

            // Get exports if any outputs have export names and query for importing stacks in parallel
            let exports_with_names: Vec<_> = outputs.iter()
                .filter_map(|output| {
                    output.export_name.as_ref().map(|export_name| (output, export_name))
                })
                .collect();
            
            let exports = if !exports_with_names.is_empty() {
                // Create futures for all import queries
                let import_tasks: Vec<_> = exports_with_names.iter()
                    .map(|(_, export_name)| {
                        let client = client.clone();
                        let export_name = (*export_name).clone();
                        tokio::spawn(async move {
                            match client
                                .list_imports()
                                .export_name(export_name)
                                .send()
                                .await
                            {
                                Ok(import_resp) => import_resp.imports.unwrap_or_default(),
                                Err(_) => vec![], // If we can't query imports, continue without them
                            }
                        })
                    })
                    .collect();
                
                // Wait for all tasks to complete
                let mut import_results = Vec::new();
                for task in import_tasks {
                    match task.await {
                        Ok(imports) => import_results.push(imports),
                        Err(_) => import_results.push(vec![]),
                    }
                }
                
                // Combine outputs with import results using conversion helper
                let stack_id = stack.stack_id.clone().unwrap_or_default();
                exports_with_names.iter()
                    .zip(import_results.iter())
                    .filter_map(|((output, _), importing_stacks)| {
                        crate::output::aws_conversion::create_stack_export(
                            output, 
                            &stack_id, 
                            importing_stacks.clone()
                        )
                    })
                    .collect()
            } else {
                vec![]
            };

            // Current status
            let current_status = StackStatusInfo {
                status: stack.stack_status.map(|s| s.as_str().to_string()).unwrap_or_default(),
                status_reason: stack.stack_status_reason,
                timestamp: stack.last_updated_time.or(stack.creation_time).and_then(|ts| {
                    chrono::DateTime::from_timestamp(ts.secs(), ts.subsec_nanos())
                }),
            };

            let stack_contents = StackContents {
                resources,
                outputs,
                exports,
                current_status,
                pending_changesets: vec![], // Would need separate query
            };

            let _ = tx.send(OutputData::StackContents(stack_contents));
            Ok::<(), anyhow::Error>(())
        })
    };
    
    // Drop the original sender so the receiver knows when all tasks are done
    drop(sender);
    
    // Process and render all data from parallel operations
    output_manager.stop().await?;
    
    // Wait for all tasks to complete and handle any errors
    let (stack_result, events_result, contents_result) = tokio::join!(
        stack_task,
        events_task, 
        contents_task
    );
    
    // Propagate any errors from the spawned tasks
    stack_result??;
    events_result??;
    contents_result??;

    Ok(())
}

#[cfg(test)]
mod tests {
    // Tests for this module are now primarily in the output conversion utilities
    // and renderer integration tests. The describe_stack function is tested end-to-end
    // through the data-driven output architecture.
}
