//! Fixture loading for output renderer testing
//!
//! Loads realistic test data from YAML files to enable comprehensive
//! testing of all output modes without requiring AWS API access.

use crate::output::data::*;
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// Default number of previous events for fixtures
const DEFAULT_FIXTURE_EVENTS_COUNT: usize = 10;

/// Test fixture structure matching the design spec
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TestFixture {
    pub name: String,
    pub description: String,
    pub tokens: FixtureTokens,
    pub aws_responses: AwsResponseSet,
    pub expected_outputs: HashMap<String, ExpectedOutput>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FixtureTokens {
    pub primary: String,
    pub derived: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AwsResponseSet {
    pub describe_stacks: Option<serde_yaml::Value>,
    pub describe_stack_events: Option<serde_yaml::Value>,
    pub describe_stack_resources: Option<serde_yaml::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpectedOutput {
    pub stdout: String,
    pub stderr: Option<String>,
    pub exit_code: i32,
}

/// Load sample data from YAML fixtures
pub struct FixtureLoader {
    fixtures_dir: String,
}

impl FixtureLoader {
    pub fn new() -> Self {
        Self {
            fixtures_dir: "tests/fixtures".to_string(),
        }
    }

    /// Load a complete test fixture
    pub fn load_test_fixture(&self, fixture_name: &str) -> Result<TestFixture> {
        let path = format!("{}/{}.yaml", self.fixtures_dir, fixture_name);
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("Failed to read fixture file: {path}"))?;

        serde_yaml::from_str(&content)
            .with_context(|| format!("Failed to parse YAML fixture: {path}"))
    }

    /// Convert test fixture to OutputData structures
    pub fn fixture_to_output_data(&self, fixture: &TestFixture) -> Result<Vec<OutputData>> {
        let mut data = Vec::new();

        // Create command metadata from fixture
        let command_metadata = CommandMetadata {
            iidy_environment: "test".to_string(),
            region: "us-east-1".to_string(),
            profile: Some("test-profile".to_string()),
            cli_arguments: {
                let mut args = HashMap::new();
                args.insert("region".to_string(), "us-east-1".to_string());
                args.insert("profile".to_string(), "test-profile".to_string());
                args.insert("argsfile".to_string(), "stack-args.yaml".to_string());
                args
            },
            iam_service_role: Some("arn:aws:iam::123456789012:role/CloudFormationRole".to_string()),
            current_iam_principal: "arn:aws:iam::123456789012:user/test-user".to_string(),
            credential_source: "profile 'test-profile' (default)".to_string(),
            iidy_version: "1.0.0".to_string(),
            primary_token: TokenInfo {
                value: fixture.tokens.primary.clone(),
                source: TokenSource::AutoGenerated,
                operation_id: "op-001".to_string(),
            },
            derived_tokens: fixture
                .tokens
                .derived
                .iter()
                .map(|(step, token)| TokenInfo {
                    value: token.clone(),
                    source: TokenSource::Derived {
                        from: fixture.tokens.primary.clone(),
                        step: step.clone(),
                    },
                    operation_id: format!("op-001-{step}"),
                })
                .collect(),
        };
        data.push(OutputData::CommandMetadata(command_metadata));

        // Create stack definition from AWS response
        if let Some(stacks_response) = &fixture.aws_responses.describe_stacks
            && let Some(stacks) = stacks_response.get("stacks")
            && let Some(stack_array) = stacks.as_sequence()
            && let Some(stack) = stack_array.first()
        {
            let stack_def = self.aws_stack_to_stack_definition(stack)?;
            data.push(OutputData::StackDefinition(stack_def, true));
        }

        // Create stack events from AWS response
        if let Some(events_response) = &fixture.aws_responses.describe_stack_events
            && let Some(events) = events_response.get("stack_events")
        {
            let stack_events = self.aws_events_to_stack_events_display(events)?;
            data.push(OutputData::StackEvents(stack_events));
        }

        // Create stack contents from AWS responses
        if let Some(resources_response) = &fixture.aws_responses.describe_stack_resources
            && let Some(resources) = resources_response.get("stack_resources")
        {
            let stack_contents = self.aws_resources_to_stack_contents(resources)?;
            data.push(OutputData::StackContents(stack_contents));
        }

        // Add command result
        data.push(OutputData::CommandResult(CommandResult {
            success: true,
            elapsed_seconds: 347,
            message: Some("Stack creation completed successfully".to_string()),
            exit_code: 0,
        }));

        Ok(data)
    }

    /// Load the main happy path fixture for development
    pub fn load_happy_path_data(&self) -> Result<Vec<OutputData>> {
        let fixture = self.load_test_fixture("create-stack-happy-path")?;
        self.fixture_to_output_data(&fixture)
    }

    /// Convert AWS stack response to StackDefinition
    fn aws_stack_to_stack_definition(&self, stack: &serde_yaml::Value) -> Result<StackDefinition> {
        Ok(StackDefinition {
            name: stack
                .get("stack_name")
                .and_then(|v| v.as_str())
                .unwrap_or("unknown")
                .to_string(),
            stackset_name: None,
            description: stack
                .get("description")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            status: stack
                .get("stack_status")
                .and_then(|v| v.as_str())
                .unwrap_or("UNKNOWN")
                .to_string(),
            status_reason: stack
                .get("stack_status_reason")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            capabilities: stack
                .get("capabilities")
                .and_then(|v| v.as_sequence())
                .map(|seq| {
                    seq.iter()
                        .filter_map(|v| v.as_str())
                        .map(|s| s.to_string())
                        .collect()
                })
                .unwrap_or_default(),
            service_role: stack
                .get("role_arn")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string()),
            tags: stack
                .get("tags")
                .and_then(|v| v.as_sequence())
                .map(|seq| {
                    let mut tags = HashMap::new();
                    for tag in seq {
                        if let (Some(key), Some(value)) = (
                            tag.get("key").and_then(|v| v.as_str()),
                            tag.get("value").and_then(|v| v.as_str()),
                        ) {
                            tags.insert(key.to_string(), value.to_string());
                        }
                    }
                    tags
                })
                .unwrap_or_default(),
            parameters: stack
                .get("parameters")
                .and_then(|v| v.as_sequence())
                .map(|seq| {
                    let mut params = HashMap::new();
                    for param in seq {
                        if let (Some(key), Some(value)) = (
                            param.get("parameter_key").and_then(|v| v.as_str()),
                            param.get("parameter_value").and_then(|v| v.as_str()),
                        ) {
                            params.insert(key.to_string(), value.to_string());
                        }
                    }
                    params
                })
                .unwrap_or_default(),
            disable_rollback: stack
                .get("disable_rollback")
                .and_then(|v| v.as_bool())
                .unwrap_or(false),
            termination_protection: stack
                .get("enable_termination_protection")
                .and_then(|v| v.as_bool())
                .unwrap_or(false),
            creation_time: stack
                .get("creation_time")
                .and_then(|v| v.as_str())
                .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
                .map(|dt| dt.with_timezone(&chrono::Utc)),
            last_updated_time: stack
                .get("last_updated_time")
                .and_then(|v| v.as_str())
                .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
                .map(|dt| dt.with_timezone(&chrono::Utc)),
            timeout_in_minutes: stack
                .get("timeout_in_minutes")
                .and_then(|v| v.as_i64())
                .map(|i| i as i32),
            notification_arns: Vec::new(),
            stack_policy: None,
            arn: stack
                .get("stack_id")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string(),
            console_url: format!(
                "https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId={}",
                stack
                    .get("stack_id")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .replace(":", "%3A")
                    .replace("/", "%2F")
            ),
            region: stack
                .get("stack_id")
                .and_then(|v| v.as_str())
                .and_then(|arn| arn.split(':').nth(3))
                .unwrap_or("us-east-1")
                .to_string(),
        })
    }

    /// Convert AWS events response to StackEventsDisplay
    fn aws_events_to_stack_events_display(
        &self,
        events: &serde_yaml::Value,
    ) -> Result<StackEventsDisplay> {
        let events_vec = if let Some(seq) = events.as_sequence() {
            seq.iter()
                .map(|event| StackEventWithTiming {
                    event: StackEvent {
                        event_id: event
                            .get("event_id")
                            .and_then(|v| v.as_str())
                            .unwrap_or("")
                            .to_string(),
                        stack_id: event
                            .get("stack_id")
                            .and_then(|v| v.as_str())
                            .unwrap_or("")
                            .to_string(),
                        stack_name: event
                            .get("stack_name")
                            .and_then(|v| v.as_str())
                            .unwrap_or("")
                            .to_string(),
                        logical_resource_id: event
                            .get("logical_resource_id")
                            .and_then(|v| v.as_str())
                            .unwrap_or("")
                            .to_string(),
                        physical_resource_id: event
                            .get("physical_resource_id")
                            .and_then(|v| v.as_str())
                            .map(|s| s.to_string()),
                        resource_type: event
                            .get("resource_type")
                            .and_then(|v| v.as_str())
                            .unwrap_or("")
                            .to_string(),
                        timestamp: event
                            .get("timestamp")
                            .and_then(|v| v.as_str())
                            .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
                            .map(|dt| dt.with_timezone(&chrono::Utc)),
                        resource_status: event
                            .get("resource_status")
                            .and_then(|v| v.as_str())
                            .unwrap_or("")
                            .to_string(),
                        resource_status_reason: event
                            .get("resource_status_reason")
                            .and_then(|v| v.as_str())
                            .map(|s| s.to_string()),
                        resource_properties: None,
                        client_request_token: event
                            .get("client_request_token")
                            .and_then(|v| v.as_str())
                            .map(|s| s.to_string()),
                    },
                    duration_seconds: match event
                        .get("logical_resource_id")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                    {
                        "test-stack" => Some(300),
                        "MyBucket" => Some(45),
                        "MySecurityGroup" => Some(20),
                        _ => None,
                    },
                })
                .collect()
        } else {
            Vec::new()
        };

        Ok(StackEventsDisplay {
            title: format!("Previous Stack Events (max {DEFAULT_FIXTURE_EVENTS_COUNT}):"),
            events: events_vec,
            max_events: Some(DEFAULT_FIXTURE_EVENTS_COUNT),
            truncated: Some(TruncationInfo { shown: 4, total: 8 }),
        })
    }

    /// Convert AWS resources response to StackContents  
    fn aws_resources_to_stack_contents(
        &self,
        resources: &serde_yaml::Value,
    ) -> Result<StackContents> {
        let resources_vec = if let Some(seq) = resources.as_sequence() {
            seq.iter()
                .map(|resource| StackResourceInfo {
                    logical_resource_id: resource
                        .get("logical_resource_id")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .to_string(),
                    physical_resource_id: resource
                        .get("physical_resource_id")
                        .and_then(|v| v.as_str())
                        .map(|s| s.to_string()),
                    resource_type: resource
                        .get("resource_type")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .to_string(),
                    resource_status: resource
                        .get("resource_status")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .to_string(),
                    resource_status_reason: None,
                    last_updated_timestamp: resource
                        .get("timestamp")
                        .and_then(|v| v.as_str())
                        .and_then(|s| chrono::DateTime::parse_from_rfc3339(s).ok())
                        .map(|dt| dt.with_timezone(&chrono::Utc)),
                })
                .collect()
        } else {
            Vec::new()
        };

        // Mock outputs and other content
        let outputs = vec![
            StackOutputInfo {
                output_key: "BucketName".to_string(),
                output_value: "test-stack-mybucket-1a2b3c4d5e6f".to_string(),
                description: Some("The name of the S3 bucket".to_string()),
                export_name: Some("test-stack-bucket-name".to_string()),
            },
            StackOutputInfo {
                output_key: "InstanceId".to_string(),
                output_value: "i-0123456789abcdef0".to_string(),
                description: Some("The ID of the EC2 instance".to_string()),
                export_name: None,
            },
        ];

        let exports = vec![
            StackExportInfo {
                name: "test-stack-bucket-name".to_string(),
                value: "test-stack-mybucket-1a2b3c4d5e6f".to_string(),
                exporting_stack_id: "arn:aws:cloudformation:us-east-1:123456789012:stack/test-stack/12345678-1234-1234-1234-123456789012".to_string(),
                importing_stacks: vec![],
            },
        ];

        Ok(StackContents {
            resources: resources_vec,
            outputs,
            exports,
            current_status: StackStatusInfo {
                status: "CREATE_COMPLETE".to_string(),
                status_reason: Some("Stack creation completed successfully".to_string()),
                timestamp: Some(chrono::Utc::now()),
            },
            pending_changesets: vec![],
        })
    }
}

impl Default for FixtureLoader {
    fn default() -> Self {
        Self::new()
    }
}
