//! Layer 3 End-to-End Tests: DynamicOutputManager with Mode Switching
//!
//! This test suite validates the complete DynamicOutputManager functionality
//! including event buffering, mode switching, event replay, and end-to-end
//! scenarios that simulate real CloudFormation operations.

use iidy::output::data::*;
use iidy::output::fixtures::FixtureLoader;
use iidy::output::manager::{DynamicOutputManager, OutputOptions};
use iidy::output::renderer::OutputMode;
use chrono::Utc;
use std::collections::HashMap;
use tokio;

/// Helper function to create test output options
fn create_test_output_options() -> OutputOptions {
    OutputOptions::minimal()
}

/// Helper function to create sample command metadata
fn create_sample_command_metadata() -> CommandMetadata {
    CommandMetadata {
        iidy_environment: "test".to_string(),
        region: "us-east-1".to_string(),
        profile: Some("test-profile".to_string()),
        cli_arguments: [
            ("argsfile".to_string(), "stack-args.yaml".to_string()),
            ("template".to_string(), "template.yaml".to_string()),
        ].into_iter().collect(),
        iam_service_role: None,
        current_iam_principal: "arn:aws:iam::123456789012:user/test-user".to_string(),
        iidy_version: "2.0.0".to_string(),
        primary_token: TokenInfo {
            value: "test-token-001".to_string(),
            source: TokenSource::AutoGenerated,
            operation_id: "create-stack-001".to_string(),
        },
        derived_tokens: vec![],
    }
}

/// Helper function to create sample status update
fn create_sample_status_update(message: &str, level: StatusLevel) -> StatusUpdate {
    StatusUpdate {
        message: message.to_string(),
        timestamp: Utc::now(),
        level,
    }
}

#[tokio::test]
async fn test_dynamic_output_manager_creation_and_initialization() {
    // Test creation with Plain mode
    let options = create_test_output_options();
    let manager = DynamicOutputManager::new(OutputMode::Plain, options.clone()).await
        .expect("Should create DynamicOutputManager with Plain mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Plain);
    assert_eq!(manager.buffer_len(), 0);
    
    // Test creation with Interactive mode
    let manager = DynamicOutputManager::new(OutputMode::Interactive, options.clone()).await
        .expect("Should create DynamicOutputManager with Interactive mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Interactive);
    assert_eq!(manager.buffer_len(), 0);
    
    // Test creation with JSON mode
    let manager = DynamicOutputManager::new(OutputMode::Json, options).await
        .expect("Should create DynamicOutputManager with JSON mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Json);
    assert_eq!(manager.buffer_len(), 0);
}

#[tokio::test]
async fn test_basic_rendering_and_buffering() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options).await
        .expect("Should create manager");
    
    // Render some data
    let metadata = create_sample_command_metadata();
    manager.render(OutputData::CommandMetadata(metadata)).await
        .expect("Should render command metadata");
    
    assert_eq!(manager.buffer_len(), 1, "Should have 1 buffered event");
    
    // Render a status update
    let status = create_sample_status_update("Operation starting", StatusLevel::Info);
    manager.render(OutputData::StatusUpdate(status)).await
        .expect("Should render status update");
    
    assert_eq!(manager.buffer_len(), 2, "Should have 2 buffered events");
}

#[tokio::test]
async fn test_buffer_limit_enforcement() {
    let mut options = create_test_output_options();
    options.buffer_limit = 3; // Very small buffer for testing
    
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options).await
        .expect("Should create manager");
    
    // Add events beyond buffer limit
    for i in 0..5 {
        let status = create_sample_status_update(&format!("Event {}", i), StatusLevel::Info);
        manager.render(OutputData::StatusUpdate(status)).await
            .expect("Should render status");
    }
    
    // Buffer should be at limit
    assert_eq!(manager.buffer_len(), 3, "Buffer should be at limit of 3");
    
    // Add one more event
    let final_status = create_sample_status_update("Final event", StatusLevel::Info);
    manager.render(OutputData::StatusUpdate(final_status)).await
        .expect("Should render final status");
    
    // Buffer should still be at limit (oldest event removed)
    assert_eq!(manager.buffer_len(), 3, "Buffer should still be at limit after overflow");
}

#[tokio::test]
async fn test_mode_switching_basic() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options).await
        .expect("Should create manager");
    
    // Start in Plain mode
    assert_eq!(manager.current_mode(), OutputMode::Plain);
    
    // Switch to Interactive mode
    manager.switch_to_mode(OutputMode::Interactive).await
        .expect("Should switch to Interactive mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Interactive, "Should be in Interactive mode");
    
    // Switch back to Plain mode
    manager.switch_to_mode(OutputMode::Plain).await
        .expect("Should switch back to Plain mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Plain, "Should be back in Plain mode");
}

#[tokio::test]
async fn test_mode_switching_with_event_replay() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options).await
        .expect("Should create manager");
    
    // Render some data in Plain mode
    let metadata = create_sample_command_metadata();
    manager.render(OutputData::CommandMetadata(metadata)).await
        .expect("Should render metadata");
    
    let status1 = create_sample_status_update("First status", StatusLevel::Info);
    manager.render(OutputData::StatusUpdate(status1)).await
        .expect("Should render first status");
    
    let status2 = create_sample_status_update("Second status", StatusLevel::Success);
    manager.render(OutputData::StatusUpdate(status2)).await
        .expect("Should render second status");
    
    assert_eq!(manager.buffer_len(), 3, "Should have 3 buffered events");
    
    // Switch to Interactive mode - this should replay all buffered events
    manager.switch_to_mode(OutputMode::Interactive).await
        .expect("Should switch to Interactive mode and replay events");
    
    // Buffer should still contain the original events plus the mode switch notification
    assert!(manager.buffer_len() >= 3, "Should have at least original events");
    assert_eq!(manager.current_mode(), OutputMode::Interactive);
    
    // Render additional data in Interactive mode
    let status3 = create_sample_status_update("Third status", StatusLevel::Warning);
    manager.render(OutputData::StatusUpdate(status3)).await
        .expect("Should render third status");
    
    assert!(manager.buffer_len() >= 4, "Should have additional events");
}

#[tokio::test]
async fn test_mode_switching_no_op_when_same_mode() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options).await
        .expect("Should create manager");
    
    // Add some events
    let metadata = create_sample_command_metadata();
    manager.render(OutputData::CommandMetadata(metadata)).await
        .expect("Should render metadata");
    
    let initial_buffer_len = manager.buffer_len();
    
    // Switch to same mode (should be no-op)
    manager.switch_to_mode(OutputMode::Plain).await
        .expect("Should handle switching to same mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Plain);
    assert_eq!(manager.buffer_len(), initial_buffer_len, "Buffer length should not change");
}

#[tokio::test]
async fn test_buffer_management_operations() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options).await
        .expect("Should create manager");
    
    // Add some events
    for i in 0..5 {
        let status = create_sample_status_update(&format!("Event {}", i), StatusLevel::Info);
        manager.render(OutputData::StatusUpdate(status)).await
            .expect("Should render status");
    }
    
    assert_eq!(manager.buffer_len(), 5, "Should have 5 buffered events");
    
    // Clear buffer
    manager.clear_buffer();
    assert_eq!(manager.buffer_len(), 0, "Buffer should be empty after clear");
    
    // Add more events after clear
    let status = create_sample_status_update("After clear", StatusLevel::Info);
    manager.render(OutputData::StatusUpdate(status)).await
        .expect("Should render after clear");
    
    assert_eq!(manager.buffer_len(), 1, "Should have 1 event after clear and render");
}

#[tokio::test]
async fn test_all_output_data_types_rendering() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Interactive, options).await
        .expect("Should create manager");
    
    // Test CommandMetadata
    let metadata = create_sample_command_metadata();
    manager.render(OutputData::CommandMetadata(metadata)).await
        .expect("Should render CommandMetadata");
    
    // Test StackDefinition
    let stack_def = StackDefinition {
        name: "test-stack".to_string(),
        stackset_name: None,
        description: Some("Test stack".to_string()),
        status: "CREATE_COMPLETE".to_string(),
        capabilities: vec!["CAPABILITY_IAM".to_string()],
        service_role: None,
        tags: HashMap::new(),
        parameters: HashMap::new(),
        disable_rollback: false,
        termination_protection: false,
        creation_time: Some(Utc::now()),
        last_updated_time: None,
        timeout_in_minutes: Some(30),
        notification_arns: vec![],
        stack_policy: None,
        arn: "arn:aws:cloudformation:us-east-1:123456789012:stack/test-stack/id".to_string(),
        console_url: "https://console.aws.amazon.com/cloudformation".to_string(),
        region: "us-east-1".to_string(),
    };
    manager.render(OutputData::StackDefinition(stack_def, true)).await
        .expect("Should render StackDefinition");
    
    // Test StatusUpdate
    let status = create_sample_status_update("Test status", StatusLevel::Info);
    manager.render(OutputData::StatusUpdate(status)).await
        .expect("Should render StatusUpdate");
    
    // Test CommandResult
    let result = CommandResult {
        success: true,
        elapsed_seconds: 120,
        message: Some("Operation completed".to_string()),
        exit_code: 0,
    };
    manager.render(OutputData::CommandResult(result)).await
        .expect("Should render CommandResult");
    
    // Test ErrorInfo
    let error = ErrorInfo {
        error_type: "TestError".to_string(),
        message: "Test error message".to_string(),
        details: Some("Error details".to_string()),
        timestamp: Utc::now(),
        suggestions: vec!["Try again".to_string()],
    };
    manager.render(OutputData::Error(error)).await
        .expect("Should render ErrorInfo");
    
    assert_eq!(manager.buffer_len(), 5, "Should have rendered 5 different data types");
}

#[tokio::test]
async fn test_end_to_end_cloudformation_operation_simulation() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options).await
        .expect("Should create manager");
    
    // Simulate a complete CloudFormation create-stack operation
    
    // 1. Command Metadata
    let metadata = create_sample_command_metadata();
    manager.render(OutputData::CommandMetadata(metadata)).await
        .expect("Should render command metadata");
    
    // 2. Stack Definition
    let stack_def = StackDefinition {
        name: "test-infrastructure".to_string(),
        stackset_name: None,
        description: Some("Test infrastructure stack".to_string()),
        status: "CREATE_IN_PROGRESS".to_string(),
        capabilities: vec!["CAPABILITY_IAM".to_string()],
        service_role: None,
        tags: [("Environment".to_string(), "test".to_string())].into_iter().collect(),
        parameters: [("InstanceType".to_string(), "t3.micro".to_string())].into_iter().collect(),
        disable_rollback: false,
        termination_protection: false,
        creation_time: Some(Utc::now()),
        last_updated_time: None,
        timeout_in_minutes: Some(30),
        notification_arns: vec![],
        stack_policy: None,
        arn: "arn:aws:cloudformation:us-east-1:123456789012:stack/test-infrastructure/id".to_string(),
        console_url: "https://console.aws.amazon.com/cloudformation".to_string(),
        region: "us-east-1".to_string(),
    };
    manager.render(OutputData::StackDefinition(stack_def, true)).await
        .expect("Should render stack definition");
    
    // 3. Status Updates during operation
    let progress_updates = vec![
        ("Starting stack creation", StatusLevel::Info),
        ("Creating VPC", StatusLevel::Info),
        ("VPC created successfully", StatusLevel::Success),
        ("Creating security group", StatusLevel::Info),
        ("Security group created", StatusLevel::Success),
        ("Creating EC2 instance", StatusLevel::Info),
        ("EC2 instance created", StatusLevel::Success),
    ];
    
    for (message, level) in progress_updates {
        let status = create_sample_status_update(message, level);
        manager.render(OutputData::StatusUpdate(status)).await
            .expect("Should render status update");
    }
    
    // 4. Switch to Interactive mode mid-operation
    manager.switch_to_mode(OutputMode::Interactive).await
        .expect("Should switch to Interactive mode");
    
    // 5. Continue with more status updates in Interactive mode
    let final_status = create_sample_status_update("Stack creation completed", StatusLevel::Success);
    manager.render(OutputData::StatusUpdate(final_status)).await
        .expect("Should render final status");
    
    // 6. Command Result
    let result = CommandResult {
        success: true,
        elapsed_seconds: 347,
        message: Some("Stack 'test-infrastructure' created successfully".to_string()),
        exit_code: 0,
    };
    manager.render(OutputData::CommandResult(result)).await
        .expect("Should render command result");
    
    // Verify final state
    assert_eq!(manager.current_mode(), OutputMode::Interactive);
    assert!(manager.buffer_len() >= 10, "Should have substantial event history");
    
    // Switch back to Plain mode to test full replay
    manager.switch_to_mode(OutputMode::Plain).await
        .expect("Should switch back to Plain mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Plain);
}

#[tokio::test]
async fn test_json_mode_rendering_and_switching() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Json, options).await
        .expect("Should create manager in JSON mode");
    
    // Test rendering in JSON mode
    let metadata = create_sample_command_metadata();
    manager.render(OutputData::CommandMetadata(metadata)).await
        .expect("Should render command metadata in JSON");
    
    let status = create_sample_status_update("JSON mode test", StatusLevel::Info);
    manager.render(OutputData::StatusUpdate(status)).await
        .expect("Should render status update in JSON");
    
    assert_eq!(manager.buffer_len(), 2, "Should have 2 buffered events in JSON mode");
    assert_eq!(manager.current_mode(), OutputMode::Json);
    
    // Switch to Plain mode and verify replay
    manager.switch_to_mode(OutputMode::Plain).await
        .expect("Should switch from JSON to Plain mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Plain);
    assert!(manager.buffer_len() >= 2, "Should have replayed events in Plain mode");
    
    // Switch to Interactive mode
    manager.switch_to_mode(OutputMode::Interactive).await
        .expect("Should switch from Plain to Interactive mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Interactive);
    
    // Switch back to JSON mode to test full cycle
    manager.switch_to_mode(OutputMode::Json).await
        .expect("Should switch back to JSON mode");
    
    assert_eq!(manager.current_mode(), OutputMode::Json);
    
    // Add more data in JSON mode
    let result = CommandResult {
        success: true,
        elapsed_seconds: 60,
        message: Some("JSON test completed".to_string()),
        exit_code: 0,
    };
    manager.render(OutputData::CommandResult(result)).await
        .expect("Should render command result in JSON");
}

#[tokio::test]
async fn test_integration_with_fixture_data() {
    // Load real fixture data and test with DynamicOutputManager
    let loader = FixtureLoader::new();
    let fixture = loader.load_test_fixture("create-stack-happy-path")
        .expect("Should load test fixture");
    
    let output_data = loader.fixture_to_output_data(&fixture)
        .expect("Should convert fixture to OutputData");
    
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Interactive, options).await
        .expect("Should create manager");
    
    // Render all fixture data
    for data in &output_data {
        manager.render(data.clone()).await
            .expect("Should render fixture data");
    }
    
    assert_eq!(manager.buffer_len(), output_data.len(), "Should have buffered all fixture data");
    
    // Test mode switching with real data
    manager.switch_to_mode(OutputMode::Plain).await
        .expect("Should switch to Plain mode with fixture data");
    
    assert_eq!(manager.current_mode(), OutputMode::Plain);
    
    // Render additional data after mode switch
    let extra_status = create_sample_status_update("Additional operation", StatusLevel::Info);
    manager.render(OutputData::StatusUpdate(extra_status)).await
        .expect("Should render additional data");
    
    assert!(manager.buffer_len() > output_data.len(), "Should have additional data after mode switch");
}

#[tokio::test]
async fn test_error_handling_during_rendering() {
    let options = create_test_output_options();
    let mut manager = DynamicOutputManager::new(OutputMode::Plain, options).await
        .expect("Should create manager");
    
    // Test rendering error information
    let error_info = ErrorInfo {
        error_type: "ValidationError".to_string(),
        message: "Stack parameter validation failed".to_string(),
        details: Some("Parameter 'InstanceType' has invalid value".to_string()),
        timestamp: Utc::now(),
        suggestions: vec![
            "Check parameter values in stack-args.yaml".to_string(),
            "Verify instance types are available in your region".to_string(),
        ],
    };
    
    manager.render(OutputData::Error(error_info)).await
        .expect("Should render error information");
    
    assert_eq!(manager.buffer_len(), 1, "Should have buffered error");
    
    // Test that mode switching works even with errors in buffer
    manager.switch_to_mode(OutputMode::Interactive).await
        .expect("Should switch modes even with errors in buffer");
    
    assert_eq!(manager.current_mode(), OutputMode::Interactive);
}