//! Keyboard Integration Tests
//!
//! Tests the keyboard listener integration with DynamicOutputManager for
//! dynamic mode switching during CloudFormation operations.

use iidy::output::{
    DynamicOutputManager, KeyboardListener, KeyboardConfig, KeyboardCommand,
    OutputMode, CommandMetadata, TokenInfo, TokenSource, StatusUpdate, StatusLevel
};
use iidy::output::manager::OutputOptions;
use chrono::Utc;
use std::collections::HashMap;
use std::time::Duration;
use tokio;

/// Helper function to create test output options
fn create_test_output_options() -> OutputOptions {
    OutputOptions::minimal()
}

/// Helper function to create sample command metadata
fn create_sample_command_metadata() -> CommandMetadata {
    CommandMetadata {
        iidy_environment: "test".to_string(),
        region: "us-east-1".to_string(),
        profile: Some("test-profile".to_string()),
        cli_arguments: HashMap::new(),
        iam_service_role: None,
        current_iam_principal: "arn:aws:iam::123456789012:user/test-user".to_string(),
        iidy_version: "2.0.0".to_string(),
        primary_token: TokenInfo {
            value: "test-token-001".to_string(),
            source: TokenSource::AutoGenerated,
            operation_id: "create-stack-001".to_string(),
        },
        derived_tokens: vec![],
    }
}

#[tokio::test]
async fn test_keyboard_listener_tty_detection() {
    // Test that keyboard listener respects TTY detection
    let config = KeyboardConfig::default();
    let listener = KeyboardListener::new(config);
    
    // The enabled state should match TTY detection
    assert_eq!(listener.is_enabled(), iidy::output::keyboard::is_tty_environment());
}

#[tokio::test]
async fn test_keyboard_listener_disabled_in_non_tty() {
    // Create a keyboard listener that's explicitly disabled (simulates non-TTY)
    let config = KeyboardConfig {
        enabled: false,
        poll_interval: Duration::from_millis(50),
        show_help_on_start: false,
    };
    
    let mut listener = KeyboardListener::new(config);
    assert!(!listener.is_enabled());
    
    // All operations should be no-ops
    assert!(listener.start().await.is_ok());
    assert!(listener.try_recv_command().is_none());
    assert!(listener.show_help().await.is_ok());
    assert!(listener.stop().await.is_ok());
}

#[tokio::test]
async fn test_keyboard_commands_mapping() {
    // Test that keyboard commands map correctly to output modes
    assert_eq!(
        KeyboardListener::command_to_output_mode(&KeyboardCommand::SwitchToPlain),
        Some(OutputMode::Plain)
    );
    assert_eq!(
        KeyboardListener::command_to_output_mode(&KeyboardCommand::SwitchToInteractive),
        Some(OutputMode::Interactive)
    );
    assert_eq!(
        KeyboardListener::command_to_output_mode(&KeyboardCommand::SwitchToJson),
        Some(OutputMode::Json)
    );
    
    // Non-mode commands should return None
    assert_eq!(
        KeyboardListener::command_to_output_mode(&KeyboardCommand::ShowHelp),
        None
    );
    assert_eq!(
        KeyboardListener::command_to_output_mode(&KeyboardCommand::Quit),
        None
    );
    assert_eq!(
        KeyboardListener::command_to_output_mode(&KeyboardCommand::ToggleTimestamps),
        None
    );
}

#[tokio::test]
async fn test_integration_with_output_manager() {
    // Test integration between keyboard listener and output manager
    let output_options = create_test_output_options();
    let mut output_manager = DynamicOutputManager::new(OutputMode::Plain, output_options).await
        .expect("Should create output manager");
    
    // Create a disabled keyboard listener for testing
    let keyboard_config = KeyboardConfig {
        enabled: false,
        poll_interval: Duration::from_millis(50),
        show_help_on_start: false,
    };
    let mut keyboard_listener = KeyboardListener::new(keyboard_config);
    
    // Verify initial state
    assert_eq!(output_manager.current_mode(), OutputMode::Plain);
    assert!(!keyboard_listener.is_enabled());
    
    // Test the integration function with disabled keyboard
    let continue_processing = iidy::output::keyboard::handle_keyboard_commands(
        &mut keyboard_listener,
        &mut output_manager
    ).await.expect("Should handle keyboard commands");
    
    // Should continue processing when keyboard is disabled
    assert!(continue_processing);
    assert_eq!(output_manager.current_mode(), OutputMode::Plain);
}

#[tokio::test]
async fn test_keyboard_listener_lifecycle() {
    // Test the complete lifecycle of a keyboard listener
    let config = KeyboardConfig {
        enabled: false, // Disable to avoid interfering with test environment
        poll_interval: Duration::from_millis(50),
        show_help_on_start: false,
    };
    
    let mut listener = KeyboardListener::new(config);
    
    // Test initialization
    assert!(listener.start().await.is_ok());
    
    // Test command reception (should be None when disabled)
    assert!(listener.try_recv_command().is_none());
    
    // Test cleanup
    assert!(listener.stop().await.is_ok());
}

#[tokio::test]
async fn test_end_to_end_mode_switching_simulation() {
    // Simulate a complete CloudFormation operation with mode switching
    let output_options = create_test_output_options();
    let mut output_manager = DynamicOutputManager::new(OutputMode::Interactive, output_options).await
        .expect("Should create output manager");
    
    // Render some initial data
    let metadata = create_sample_command_metadata();
    output_manager.render(iidy::output::OutputData::CommandMetadata(metadata)).await
        .expect("Should render initial metadata");
    
    assert_eq!(output_manager.current_mode(), OutputMode::Interactive);
    assert_eq!(output_manager.buffer_len(), 1);
    
    // Simulate mode switches (without actual keyboard input)
    output_manager.switch_to_mode(OutputMode::Plain).await
        .expect("Should switch to Plain mode");
    assert_eq!(output_manager.current_mode(), OutputMode::Plain);
    
    output_manager.switch_to_mode(OutputMode::Json).await
        .expect("Should switch to JSON mode");
    assert_eq!(output_manager.current_mode(), OutputMode::Json);
    
    // Add more data after mode switches
    let status = StatusUpdate {
        message: "Operation continuing".to_string(),
        timestamp: Utc::now(),
        level: StatusLevel::Info,
    };
    output_manager.render(iidy::output::OutputData::StatusUpdate(status)).await
        .expect("Should render status after mode switch");
    
    // Verify event history is maintained
    assert!(output_manager.buffer_len() >= 2);
    
    // Switch back to Interactive mode to test full cycle
    output_manager.switch_to_mode(OutputMode::Interactive).await
        .expect("Should switch back to Interactive mode");
    assert_eq!(output_manager.current_mode(), OutputMode::Interactive);
}

#[test]
fn test_keyboard_config_validation() {
    // Test that keyboard configuration respects TTY environment
    let default_config = KeyboardConfig::default();
    assert_eq!(default_config.enabled, iidy::output::keyboard::is_tty_environment());
    assert_eq!(default_config.poll_interval, Duration::from_millis(50));
    assert!(!default_config.show_help_on_start);
    
    // Test explicit configuration
    let custom_config = KeyboardConfig {
        enabled: true,
        poll_interval: Duration::from_millis(100),
        show_help_on_start: true,
    };
    assert!(custom_config.enabled);
    assert_eq!(custom_config.poll_interval, Duration::from_millis(100));
    assert!(custom_config.show_help_on_start);
}

#[test]
fn test_create_for_environment() {
    // Test the convenience function for creating environment-appropriate listener
    let listener = iidy::output::keyboard::create_for_environment();
    assert_eq!(listener.is_enabled(), iidy::output::keyboard::is_tty_environment());
}

#[tokio::test]
async fn test_keyboard_listener_error_handling() {
    // Test that keyboard listener handles errors gracefully
    let config = KeyboardConfig {
        enabled: false, // Disabled to prevent terminal interference
        poll_interval: Duration::from_millis(50),
        show_help_on_start: false,
    };
    
    let mut listener = KeyboardListener::new(config);
    
    // All operations should succeed even when disabled
    assert!(listener.start().await.is_ok());
    assert!(listener.show_help().await.is_ok());
    assert!(listener.stop().await.is_ok());
    
    // Multiple start/stop cycles should be safe
    assert!(listener.start().await.is_ok());
    assert!(listener.start().await.is_ok()); // Should be idempotent
    assert!(listener.stop().await.is_ok());
    assert!(listener.stop().await.is_ok()); // Should be idempotent
}