use aws_sdk_cloudformation::Client;
use iidy::{
    cfn::{CfnContext, CfnRequestBuilder},
    cli::AwsOpts,
    timing::{ReliableTimeProvider, TimeProvider, TokenInfo, TokenSource},
};
use std::sync::Arc;

/// Integration test demonstrating the complete token management workflow.
///
/// This test verifies that the token system works end-to-end without
/// requiring actual AWS credentials or network calls.
#[tokio::test]
async fn test_token_management_integration() {
    // Test 1: AwsOpts normalization
    let aws_opts = AwsOpts {
        region: Some("us-east-1".to_string()),
        profile: None,
        assume_role_arn: None,
        client_request_token: Some("user-provided-token-123".to_string()),
    };

    let normalized = aws_opts.normalize();

    // Verify normalized options
    assert_eq!(normalized.region.as_deref(), Some("us-east-1"));
    assert_eq!(
        normalized.client_request_token.value,
        "user-provided-token-123"
    );
    assert!(matches!(
        normalized.client_request_token.source,
        TokenSource::UserProvided
    ));

    // Test 2: Auto-generated token normalization
    let aws_opts_auto = AwsOpts {
        region: Some("us-west-2".to_string()),
        profile: None,
        assume_role_arn: None,
        client_request_token: None,
    };

    let normalized_auto = aws_opts_auto.normalize();

    // Verify auto-generated token
    assert!(!normalized_auto.client_request_token.value.is_empty());
    assert!(matches!(
        normalized_auto.client_request_token.source,
        TokenSource::AutoGenerated
    ));

    // Test 3: Token derivation consistency
    let primary_token =
        TokenInfo::user_provided("test-primary-token".to_string(), "test-op".to_string());

    let derived1 = primary_token.derive_for_step("create-changeset");
    let derived2 = primary_token.derive_for_step("create-changeset");
    let derived3 = primary_token.derive_for_step("execute-changeset");

    // Same step should produce same token
    assert_eq!(derived1.value, derived2.value);
    // Different steps should produce different tokens
    assert_ne!(derived1.value, derived3.value);
    // Both should be derived from same source
    assert_eq!(derived1.root_token(), derived3.root_token());

    // Test 4: CfnContext with mock client
    let config = aws_config::SdkConfig::builder()
        .region(aws_types::region::Region::new("us-east-1"))
        .behavior_version(aws_config::BehaviorVersion::latest())
        .build();
    let client = Client::new(&config);

    let time_provider: Arc<dyn TimeProvider> = Arc::new(ReliableTimeProvider::new());
    let token_info = TokenInfo::user_provided(
        "integration-test-token".to_string(),
        "integration-test".to_string(),
    );

    let context = CfnContext::new_without_start_time(client, time_provider, token_info.clone());

    // Verify context setup
    assert_eq!(context.primary_token().value, "integration-test-token");
    assert!(!context.has_derived_tokens());

    // Test 5: Token derivation in context
    let create_token = context.derive_token_for_step("create-changeset");
    let execute_token = context.derive_token_for_step("execute-changeset");

    // Verify derivation
    assert!(create_token.is_derived());
    assert!(execute_token.is_derived());
    assert_ne!(create_token.value, execute_token.value);
    assert!(context.has_derived_tokens());

    // Verify token tracking
    let used_tokens = context.get_used_tokens();
    assert_eq!(used_tokens.len(), 3); // Primary + 2 derived

    // Test 6: CfnRequestBuilder integration
    let mock_stack_args = create_mock_stack_args();
    let builder = CfnRequestBuilder::new(&context, &mock_stack_args);

    // Test request building with token injection
    let (_create_request, create_token) = builder.build_create_stack("test-create", "test-stack-args.yaml", Some("test")).await.unwrap();
    let (_update_request, update_token) = builder.build_update_stack("test-update");
    let (_changeset_request, changeset_token) =
        builder.build_create_changeset("test-changeset", "test-changeset");

    // Verify all tokens are different but correlated
    assert_ne!(create_token.value, update_token.value);
    assert_ne!(create_token.value, changeset_token.value);
    assert_ne!(update_token.value, changeset_token.value);

    // All should have same operation ID
    assert_eq!(create_token.operation_id, update_token.operation_id);
    assert_eq!(create_token.operation_id, changeset_token.operation_id);

    // All should be derived from same root
    assert_eq!(create_token.root_token(), update_token.root_token());
    assert_eq!(create_token.root_token(), changeset_token.root_token());

    println!("✅ Token management integration test completed successfully");
    println!("   Primary token: {}", context.primary_token().value);
    println!(
        "   Derived tokens created: {}",
        context.get_used_tokens().len() - 1
    );
    println!("   Token correlation verified across all operations");
}

/// Test the complete normalization workflow that main.rs uses.
#[test]
fn test_main_normalization_workflow() {
    // Simulate what main.rs does
    let cli_aws_opts = AwsOpts {
        region: Some("eu-west-1".to_string()),
        profile: Some("production".to_string()),
        assume_role_arn: Some("arn:aws:iam::123456789012:role/deploy".to_string()),
        client_request_token: None,
    };

    // This is what main.rs does for each command
    let normalized = cli_aws_opts.normalize();

    // Verify the normalization preserves all AWS config
    assert_eq!(normalized.region.as_deref(), Some("eu-west-1"));
    assert_eq!(normalized.profile.as_deref(), Some("production"));
    assert_eq!(
        normalized.assume_role_arn.as_deref(),
        Some("arn:aws:iam::123456789012:role/deploy")
    );

    // Verify token is always present after normalization
    assert!(!normalized.client_request_token.value.is_empty());
    assert!(matches!(
        normalized.client_request_token.source,
        TokenSource::AutoGenerated
    ));

    // Verify token is UUID format
    assert!(normalized.client_request_token.value.contains('-'));
    assert!(normalized.client_request_token.value.len() >= 36); // UUID length

    println!("✅ Main.rs normalization workflow test completed");
    println!(
        "   Generated token: {}",
        normalized.client_request_token.value
    );
    println!("   All AWS config preserved through normalization");
}

/// Test token display format for copy-paste friendliness.
#[test]
fn test_token_display_format() {
    let primary = TokenInfo::user_provided(
        "abc123ef-4567-89ab-cdef-0123456789ab".to_string(),
        "test-op".to_string(),
    );
    let derived = primary.derive_for_step("create-changeset");

    // Verify derived token format is copy-paste friendly
    assert!(derived.value.starts_with("abc123ef-")); // Starts with primary prefix
    assert!(derived.value.contains('-')); // Contains hyphens, no colons
    assert!(!derived.value.contains(':')); // No colons that break terminal selection
    assert!(!derived.value.contains(' ')); // No spaces

    // Verify token can be split on hyphens (terminal-friendly)
    let parts: Vec<&str> = derived.value.split('-').collect();
    assert_eq!(parts.len(), 2); // prefix-suffix format
    assert_eq!(parts[0], "abc123ef");
    assert_eq!(parts[1].len(), 8); // 8 hex characters

    // Verify hex format
    assert!(parts[1].chars().all(|c| c.is_ascii_hexdigit()));

    println!("✅ Token display format test completed");
    println!("   Primary: {}", primary.value);
    println!("   Derived: {}", derived.value);
    println!("   Format verified as copy-paste friendly");
}

fn create_mock_stack_args() -> iidy::stack_args::StackArgs {
    use std::collections::BTreeMap;

    let mut parameters = BTreeMap::new();
    parameters.insert("Environment".to_string(), "test".to_string());

    let mut tags = BTreeMap::new();
    tags.insert("Application".to_string(), "iidy-test".to_string());

    iidy::stack_args::StackArgs {
        stack_name: Some("test-integration-stack".to_string()),
        template: Some(r#"{"Resources":{"TestResource":{"Type":"AWS::S3::Bucket"}}}"#.to_string()),
        parameters: Some(parameters),
        tags: Some(tags),
        capabilities: Some(vec!["CAPABILITY_IAM".to_string()]),
        ..Default::default()
    }
}
