//! AWS SDK response to OutputData conversion utilities
//!
//! This module provides utilities to convert AWS CloudFormation SDK responses
//! and internal iidy data structures to OutputData for the data-driven output system.

use crate::{
    cfn::CfnContext,
    output::{
        CommandMetadata, CommandResult, StatusUpdate, StatusLevel, OutputData,
        TokenInfo as OutputTokenInfo, TokenSource as OutputTokenSource,
        StackListDisplay, StackListEntry, StackDefinition, StackListColumn,
        StackEventsDisplay, StackEvent, StackEventWithTiming,
        StackResourceInfo, StackOutputInfo, StackExportInfo
    },
    cli::NormalizedAwsOpts,
    stack_args::StackArgs,
    timing::{TokenInfo as TimingTokenInfo, TokenSource as TimingTokenSource},
};
use aws_sdk_cloudformation::types::{Stack, StackEvent as AwsStackEvent, StackResource, Output};
use chrono::{Utc, DateTime};
use std::collections::HashMap;

/// Convert timing::TokenInfo to output::TokenInfo
pub fn convert_token_info(timing_token: &TimingTokenInfo) -> OutputTokenInfo {
    let source = match &timing_token.source {
        TimingTokenSource::UserProvided => OutputTokenSource::UserProvided,
        TimingTokenSource::AutoGenerated => OutputTokenSource::AutoGenerated,
        TimingTokenSource::Derived { from, step } => OutputTokenSource::Derived {
            from: from.clone(),
            step: step.clone(),
        },
    };

    OutputTokenInfo {
        value: timing_token.value.clone(),
        source,
        operation_id: timing_token.operation_id.clone(),
    }
}

/// Convert CfnContext and operation info to CommandMetadata
pub async fn create_command_metadata(
    context: &CfnContext,
    opts: &NormalizedAwsOpts,
    stack_args: &StackArgs,
    environment: &str,
) -> Result<CommandMetadata, anyhow::Error> {
    let mut cli_arguments = HashMap::new();
    
    // Add CLI arguments from opts
    if let Some(ref profile) = opts.profile {
        cli_arguments.insert("profile".to_string(), profile.clone());
    }
    if let Some(ref region) = opts.region {
        cli_arguments.insert("region".to_string(), region.clone());
    }

    // Always include the primary token, but renderers will decide whether to display it
    let primary_token = convert_token_info(&context.primary_token());
    
    // Only include derived tokens if we actually derived new ones (not just the primary)
    let all_tokens = context.get_used_tokens();
    let derived_tokens = if all_tokens.len() > 1 {
        all_tokens.into_iter().skip(1).map(|t| convert_token_info(&t)).collect()
    } else {
        vec![]
    };

    // Get current IAM principal
    let current_iam_principal = get_current_iam_principal(context).await?;

    Ok(CommandMetadata {
        iidy_environment: environment.to_string(),
        region: opts.region.clone().unwrap_or_else(|| "us-east-1".to_string()),
        profile: opts.profile.clone(),
        cli_arguments,
        iam_service_role: stack_args.role_arn.clone(),
        current_iam_principal,
        iidy_version: env!("CARGO_PKG_VERSION").to_string(),
        primary_token,
        derived_tokens,
    })
}

/// Get the current IAM principal from AWS STS
async fn get_current_iam_principal(_context: &CfnContext) -> Result<String, anyhow::Error> {
    // Create STS client - we need to get the SDK config from somewhere else
    // For now, we'll create a basic config
    let config = aws_config::load_defaults(aws_config::BehaviorVersion::latest()).await;
    let sts_client = aws_sdk_sts::Client::new(&config);
    
    match sts_client.get_caller_identity().send().await {
        Ok(response) => {
            Ok(response.arn().unwrap_or("arn:aws:iam::unknown:user/current").to_string())
        }
        Err(e) => {
            // Fall back to placeholder if STS call fails (e.g., no internet, permissions issue)
            eprintln!("Warning: Could not get current IAM principal: {}", e);
            Ok("arn:aws:iam::unknown:user/current".to_string())
        }
    }
}

/// Create a status update from a message
pub fn create_status_update(message: &str, level: StatusLevel) -> OutputData {
    OutputData::StatusUpdate(StatusUpdate {
        message: message.to_string(),
        timestamp: Utc::now(),
        level,
    })
}

/// Create a command result for operation completion
pub fn create_command_result(
    success: bool,
    elapsed_seconds: i64,
    message: Option<String>,
) -> OutputData {
    OutputData::CommandResult(CommandResult {
        success,
        elapsed_seconds: elapsed_seconds.max(0) as u64, // Convert to u64, ensuring non-negative
        message,
        exit_code: if success { 0 } else { 1 },
    })
}

/// Progress message helpers
pub fn progress_message(msg: &str) -> OutputData {
    create_status_update(msg, StatusLevel::Info)
}

pub fn success_message(msg: &str) -> OutputData {
    create_status_update(msg, StatusLevel::Success)
}

pub fn warning_message(msg: &str) -> OutputData {
    create_status_update(msg, StatusLevel::Warning)
}

pub fn error_message(msg: &str) -> OutputData {
    create_status_update(msg, StatusLevel::Error)
}

/// Convert AWS SDK Stack to StackListEntry
pub fn convert_stack_to_list_entry(stack: &Stack) -> StackListEntry {
    use chrono::{DateTime, Utc};
    
    // Convert AWS DateTime to chrono DateTime
    let creation_time = stack.creation_time().map(|aws_dt| {
        DateTime::from_timestamp(aws_dt.as_secs_f64().floor() as i64, 0).unwrap_or_else(Utc::now)
    });
    
    let last_updated_time = stack.last_updated_time().map(|aws_dt| {
        DateTime::from_timestamp(aws_dt.as_secs_f64().floor() as i64, 0).unwrap_or_else(Utc::now)
    });

    let status = stack
        .stack_status()
        .map(|s| s.as_str().to_string())
        .unwrap_or_else(|| "UNKNOWN".to_string());
        
    let name = stack.stack_name().unwrap_or("unknown").to_string();

    let tags: HashMap<String, String> = stack
        .tags()
        .iter()
        .filter_map(|t| match (t.key(), t.value()) {
            (Some(k), Some(v)) => Some((k.to_string(), v.to_string())),
            _ => None,
        })
        .collect();

    let termination_protection = stack.enable_termination_protection().unwrap_or(false);
    
    // Determine environment type based on name/tags
    let environment_type = if name.contains("production") || tags.get("environment") == Some(&"production".to_string()) {
        Some("production".to_string())
    } else if name.contains("integration") || tags.get("environment") == Some(&"integration".to_string()) {
        Some("integration".to_string())
    } else if name.contains("development") || tags.get("environment") == Some(&"development".to_string()) {
        Some("development".to_string())
    } else {
        None
    };

    StackListEntry {
        stack_name: name,
        stack_status: status,
        creation_time,
        last_updated_time,
        tags,
        status_reason: stack.stack_status_reason().map(|s| s.to_string()),
        termination_protection,
        environment_type,
    }
}

/// Convert a list of AWS SDK Stacks to StackListDisplay
pub fn convert_stacks_to_list_display(stacks: Vec<Stack>, show_tags: bool) -> OutputData {
    let mut entries: Vec<StackListEntry> = stacks.iter().map(convert_stack_to_list_entry).collect();
    
    // Sort by creation time (matching original logic)
    entries.sort_by(|a, b| a.creation_time.cmp(&b.creation_time));

    OutputData::StackList(StackListDisplay {
        stacks: entries,
        show_tags,
        filters_applied: vec![], // No filters applied by default
        columns: StackListColumn::default_columns(), // Use default columns
        query_mode: false, // Normal display mode by default
    })
}

/// Convert AWS SDK Stack to StackDefinition
pub fn convert_stack_to_definition(stack: &Stack, show_times: bool) -> OutputData {
    use chrono::{DateTime, Utc};
    
    let creation_time = stack.creation_time().map(|aws_dt| {
        DateTime::from_timestamp(aws_dt.as_secs_f64().floor() as i64, 0).unwrap_or_else(Utc::now)
    });
    
    let last_updated_time = stack.last_updated_time().map(|aws_dt| {
        DateTime::from_timestamp(aws_dt.as_secs_f64().floor() as i64, 0).unwrap_or_else(Utc::now)
    });

    let tags: HashMap<String, String> = stack
        .tags()
        .iter()
        .filter_map(|t| match (t.key(), t.value()) {
            (Some(k), Some(v)) => Some((k.to_string(), v.to_string())),
            _ => None,
        })
        .collect();

    let stack_definition = StackDefinition {
        name: stack.stack_name().unwrap_or("unknown").to_string(),
        stackset_name: None, // TODO: Determine if this is a StackSet stack
        description: stack.description().map(|s| s.to_string()),
        status: stack.stack_status().map(|s| s.as_str().to_string()).unwrap_or_else(|| "UNKNOWN".to_string()),
        capabilities: stack.capabilities().iter().map(|c| c.as_str().to_string()).collect(),
        service_role: stack.role_arn().map(|s| s.to_string()),
        tags,
        parameters: stack.parameters().iter().filter_map(|p| {
            match (p.parameter_key(), p.parameter_value()) {
                (Some(k), Some(v)) => Some((k.to_string(), v.to_string())),
                _ => None,
            }
        }).collect(),
        disable_rollback: false, // TODO: Get this information
        termination_protection: stack.enable_termination_protection().unwrap_or(false),
        creation_time,
        last_updated_time,
        timeout_in_minutes: stack.timeout_in_minutes(),
        notification_arns: stack.notification_arns().iter().map(|s| s.to_string()).collect(),
        stack_policy: None, // TODO: Fetch separately if needed
        arn: stack.stack_id().unwrap_or("unknown").to_string(), // Stack ARN is typically the ID
        console_url: format!("https://console.aws.amazon.com/cloudformation/home#/stacks/stackinfo?stackId={}", 
                           stack.stack_id().unwrap_or("unknown")),
        region: "current".to_string(), // TODO: Get actual region
    };

    OutputData::StackDefinition(stack_definition, show_times)
}

/// Convert AWS StackEvent to our StackEvent format
pub fn convert_aws_stack_event(aws_event: &AwsStackEvent) -> StackEvent {
    use chrono::{DateTime, Utc};
    
    let timestamp = aws_event.timestamp().map(|aws_dt| {
        DateTime::from_timestamp(aws_dt.as_secs_f64().floor() as i64, 0).unwrap_or_else(Utc::now)
    });

    StackEvent {
        event_id: aws_event.event_id().unwrap_or("unknown").to_string(),
        stack_id: aws_event.stack_id().unwrap_or("unknown").to_string(),
        stack_name: aws_event.stack_name().unwrap_or("unknown").to_string(),
        logical_resource_id: aws_event.logical_resource_id().unwrap_or("unknown").to_string(),
        physical_resource_id: aws_event.physical_resource_id().map(|s| s.to_string()),
        resource_type: aws_event.resource_type().unwrap_or("unknown").to_string(),
        timestamp,
        resource_status: aws_event.resource_status().map(|s| s.as_str().to_string()).unwrap_or_else(|| "UNKNOWN".to_string()),
        resource_status_reason: aws_event.resource_status_reason().map(|s| s.to_string()),
        resource_properties: aws_event.resource_properties().map(|s| s.to_string()),
        client_request_token: aws_event.client_request_token().map(|s| s.to_string()),
    }
}

/// Convert AWS stack events to StackEventsDisplay
pub fn convert_stack_events_to_display(
    events: Vec<AwsStackEvent>,
    title: &str,
) -> OutputData {
    convert_stack_events_to_display_with_max(events, title, None)
}

/// Convert AWS stack events to StackEventsDisplay with maximum event count
pub fn convert_stack_events_to_display_with_max(
    events: Vec<AwsStackEvent>,
    title: &str,
    max_events: Option<usize>,
) -> OutputData {
    let converted_events: Vec<StackEvent> = events.iter().map(convert_aws_stack_event).collect();
    
    // Calculate duration for resource operations
    let events_with_timing: Vec<StackEventWithTiming> = calculate_event_durations(converted_events);

    OutputData::StackEvents(StackEventsDisplay {
        title: title.to_string(),
        events: events_with_timing,
        max_events,
        truncated: None, // Renderers will calculate truncation after sorting/limiting
    })
}

/// Calculate durations for resource operations by matching start/complete events
fn calculate_event_durations(mut events: Vec<StackEvent>) -> Vec<StackEventWithTiming> {
    use std::collections::HashMap;
    use chrono::DateTime;
    
    // Sort events chronologically (oldest first) to properly track start/end pairs
    events.sort_by(|a, b| {
        match (&a.timestamp, &b.timestamp) {
            (Some(a_time), Some(b_time)) => a_time.cmp(b_time),
            (Some(_), None) => std::cmp::Ordering::Less,
            (None, Some(_)) => std::cmp::Ordering::Greater,
            (None, None) => std::cmp::Ordering::Equal,
        }
    });
    
    // Track start times for each resource
    let mut start_times: HashMap<String, DateTime<chrono::Utc>> = HashMap::new();
    let mut result = Vec::new();
    
    // Process events in chronological order to properly track durations
    for event in events {
        let duration_seconds = if let Some(timestamp) = &event.timestamp {
            let resource_key = format!("{}/{}", event.logical_resource_id, event.resource_type);
            
            if event.resource_status.ends_with("_IN_PROGRESS") {
                // This is a start event, record the start time
                start_times.insert(resource_key, *timestamp);
                None
            } else if event.resource_status.ends_with("_COMPLETE") || event.resource_status.ends_with("_FAILED") {
                // This is an end event, calculate duration if we have a start time
                if let Some(start_time) = start_times.get(&resource_key) {
                    let duration = timestamp.signed_duration_since(*start_time);
                    Some(duration.num_seconds().max(0) as u64)
                } else {
                    // No matching start event found - this is common for describe-stack
                    // on existing stacks where IN_PROGRESS events are outside the window
                    None
                }
            } else {
                None
            }
        } else {
            None
        };

        result.push(StackEventWithTiming {
            event,
            duration_seconds,
        });
    }
    
    result
}

/// Convert AWS SDK StackResource to StackResourceInfo
pub fn convert_stack_resource(aws_resource: &StackResource) -> StackResourceInfo {
    StackResourceInfo {
        logical_resource_id: aws_resource.logical_resource_id.clone().unwrap_or_default(),
        physical_resource_id: aws_resource.physical_resource_id.clone(),
        resource_type: aws_resource.resource_type.clone().unwrap_or_default(),
        resource_status: aws_resource.resource_status.as_ref()
            .map(|s| s.as_str().to_string())
            .unwrap_or_default(),
        resource_status_reason: aws_resource.resource_status_reason.clone(),
        last_updated_timestamp: aws_resource.timestamp.as_ref().and_then(|ts| {
            DateTime::from_timestamp(ts.secs(), ts.subsec_nanos())
        }),
    }
}

/// Convert multiple AWS SDK StackResources to Vec<StackResourceInfo>
pub fn convert_stack_resources(aws_resources: Vec<StackResource>) -> Vec<StackResourceInfo> {
    aws_resources.iter().map(convert_stack_resource).collect()
}

/// Convert AWS SDK Output to StackOutputInfo
pub fn convert_stack_output(aws_output: &Output) -> StackOutputInfo {
    StackOutputInfo {
        output_key: aws_output.output_key.clone().unwrap_or_default(),
        output_value: aws_output.output_value.clone().unwrap_or_default(),
        description: aws_output.description.clone(),
        export_name: aws_output.export_name.clone(),
    }
}

/// Convert multiple AWS SDK Outputs to Vec<StackOutputInfo>
pub fn convert_stack_outputs(aws_outputs: Vec<Output>) -> Vec<StackOutputInfo> {
    aws_outputs.iter().map(convert_stack_output).collect()
}

/// Create StackExportInfo from StackOutputInfo (for outputs with export names)
pub fn create_stack_export(
    output: &StackOutputInfo, 
    stack_id: &str, 
    importing_stacks: Vec<String>
) -> Option<StackExportInfo> {
    output.export_name.as_ref().map(|export_name| {
        StackExportInfo {
            name: export_name.clone(),
            value: output.output_value.clone(),
            exporting_stack_id: stack_id.to_string(),
            importing_stacks,
        }
    })
}

/// Convert stack outputs to exports (only outputs with export_name)
pub fn convert_outputs_to_exports(
    outputs: &[StackOutputInfo], 
    stack_id: &str
) -> Vec<StackExportInfo> {
    outputs.iter()
        .filter_map(|output| create_stack_export(output, stack_id, vec![]))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::{DateTime, Utc};
    use crate::{
        cfn::CfnContext,
        timing::{TokenInfo, MockTimeProvider},
        cli::NormalizedAwsOpts,
        stack_args::StackArgs,
    };
    use aws_sdk_cloudformation::Client;
    use std::sync::Arc;

    #[tokio::test]
    async fn test_create_command_metadata() {
        let fixed_time = chrono::Utc::now();
        let time_provider = Arc::new(MockTimeProvider::new(fixed_time));
        let config = aws_config::SdkConfig::builder()
            .region(aws_types::region::Region::new("us-east-1"))
            .behavior_version(aws_config::BehaviorVersion::latest())
            .build();
        let client = Client::new(&config);
        let token_info = TokenInfo::user_provided("test-token-123".to_string(), "test-op".to_string());
        let aws_config = aws_config::SdkConfig::builder()
            .region(aws_types::region::Region::new("us-east-1"))
            .behavior_version(aws_config::BehaviorVersion::latest())
            .build();
        let context = CfnContext::new_without_start_time(client, aws_config, time_provider, token_info);

        let opts = NormalizedAwsOpts {
            profile: Some("test-profile".to_string()),
            region: Some("us-west-2".to_string()),
            assume_role_arn: None,
            client_request_token: TokenInfo::user_provided("test-token".to_string(), "test-op".to_string()),
            fixture_set: None,
        };

        let stack_args = StackArgs {
            stack_name: Some("test-stack".to_string()),
            template: Some("template.yaml".to_string()),
            role_arn: Some("arn:aws:iam::123456789012:role/TestRole".to_string()),
            ..Default::default()
        };

        let metadata = create_command_metadata(&context, &opts, &stack_args, "test-env").await.unwrap();

        // cfn_operation is now derived from CLI context, not stored in metadata
        assert_eq!(metadata.iidy_environment, "test-env");
        assert_eq!(metadata.region, "us-west-2");
        assert_eq!(metadata.profile, Some("test-profile".to_string()));
        assert_eq!(metadata.iam_service_role, Some("arn:aws:iam::123456789012:role/TestRole".to_string()));
        assert_eq!(metadata.primary_token.value, "test-token-123");
        assert!(metadata.cli_arguments.contains_key("profile"));
        assert!(metadata.cli_arguments.contains_key("region"));
    }

    #[test]
    fn test_status_update_creation() {
        let update = create_status_update("Test message", StatusLevel::Info);
        
        if let OutputData::StatusUpdate(status) = update {
            assert_eq!(status.message, "Test message");
            assert_eq!(status.level, StatusLevel::Info);
        } else {
            panic!("Expected StatusUpdate");
        }
    }

    #[test]
    fn test_command_result_creation() {
        let result = create_command_result(true, 120, Some("Success".to_string()));
        
        if let OutputData::CommandResult(cmd_result) = result {
            assert!(cmd_result.success);
            assert_eq!(cmd_result.elapsed_seconds, 120);
            assert_eq!(cmd_result.message, Some("Success".to_string()));
            assert_eq!(cmd_result.exit_code, 0);
        } else {
            panic!("Expected CommandResult");
        }
    }

    #[test]
    fn test_helper_functions() {
        // Test all helper functions create correct OutputData types
        match progress_message("Progress") {
            OutputData::StatusUpdate(status) => {
                assert_eq!(status.message, "Progress");
                assert_eq!(status.level, StatusLevel::Info);
            }
            _ => panic!("Expected StatusUpdate"),
        }

        match success_message("Success") {
            OutputData::StatusUpdate(status) => {
                assert_eq!(status.message, "Success");
                assert_eq!(status.level, StatusLevel::Success);
            }
            _ => panic!("Expected StatusUpdate"),
        }

        match warning_message("Warning") {
            OutputData::StatusUpdate(status) => {
                assert_eq!(status.message, "Warning");
                assert_eq!(status.level, StatusLevel::Warning);
            }
            _ => panic!("Expected StatusUpdate"),
        }

        match error_message("Error") {
            OutputData::StatusUpdate(status) => {
                assert_eq!(status.message, "Error");
                assert_eq!(status.level, StatusLevel::Error);
            }
            _ => panic!("Expected StatusUpdate"),
        }
    }

    #[test]
    fn test_duration_calculation() {
        let base_time = "2023-07-10T14:00:00Z".parse::<DateTime<Utc>>().unwrap();
        
        let events = vec![
            StackEvent {
                event_id: "1".to_string(),
                stack_id: "test-stack".to_string(),
                stack_name: "test-stack".to_string(),
                logical_resource_id: "MyResource".to_string(),
                physical_resource_id: Some("resource-123".to_string()),
                resource_type: "AWS::S3::Bucket".to_string(),
                timestamp: Some(base_time),
                resource_status: "CREATE_IN_PROGRESS".to_string(),
                resource_status_reason: None,
                resource_properties: None,
                client_request_token: None,
            },
            StackEvent {
                event_id: "2".to_string(),
                stack_id: "test-stack".to_string(),
                stack_name: "test-stack".to_string(),
                logical_resource_id: "MyResource".to_string(),
                physical_resource_id: Some("resource-123".to_string()),
                resource_type: "AWS::S3::Bucket".to_string(),
                timestamp: Some(base_time + chrono::Duration::seconds(5)),
                resource_status: "CREATE_COMPLETE".to_string(),
                resource_status_reason: None,
                resource_properties: None,
                client_request_token: None,
            },
        ];

        let events_with_timing = calculate_event_durations(events);
        
        // First event (IN_PROGRESS) should have no duration
        assert_eq!(events_with_timing[0].duration_seconds, None);
        
        // Second event (COMPLETE) should have 5 second duration
        assert_eq!(events_with_timing[1].duration_seconds, Some(5));
    }
}