//! Core data structures for data-driven output architecture
//!
//! These structures capture exactly what iidy-js displays, separated from
//! presentation logic to enable multiple output modes.

use std::collections::HashMap;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Token information from the existing token management system
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TokenInfo {
    pub value: String,
    pub source: TokenSource,
    pub operation_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum TokenSource {
    UserProvided,
    AutoGenerated,
    Derived { from: String, step: String },
}

/// CloudFormation operation type
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum CfnOperation {
    CreateStack,
    UpdateStack,
    DeleteStack,
    DescribeStack,
    CreateOrUpdate,
    CreateChangeset,
    ExecuteChangeset,
    EstimateCost,
    ListStacks,
    WatchStack,
    GetStackTemplate,
    GetStackInstances,
    DescribeStackDrift,
}

impl CfnOperation {
    /// Convert from string (for backward compatibility)
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "create-stack" => Some(Self::CreateStack),
            "update-stack" => Some(Self::UpdateStack),
            "delete-stack" => Some(Self::DeleteStack),
            "describe-stack" => Some(Self::DescribeStack),
            "create-or-update" => Some(Self::CreateOrUpdate),
            "create-changeset" => Some(Self::CreateChangeset),
            "execute-changeset" => Some(Self::ExecuteChangeset),
            "estimate-cost" => Some(Self::EstimateCost),
            "list-stacks" => Some(Self::ListStacks),
            "watch-stack" => Some(Self::WatchStack),
            "get-stack-template" => Some(Self::GetStackTemplate),
            "get-stack-instances" => Some(Self::GetStackInstances),
            "describe-stack-drift" => Some(Self::DescribeStackDrift),
            _ => None,
        }
    }

    /// Convert to string for display
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::CreateStack => "create-stack",
            Self::UpdateStack => "update-stack",
            Self::DeleteStack => "delete-stack",
            Self::DescribeStack => "describe-stack",
            Self::CreateOrUpdate => "create-or-update",
            Self::CreateChangeset => "create-changeset",
            Self::ExecuteChangeset => "execute-changeset",
            Self::EstimateCost => "estimate-cost",
            Self::ListStacks => "list-stacks",
            Self::WatchStack => "watch-stack",
            Self::GetStackTemplate => "get-stack-template",
            Self::GetStackInstances => "get-stack-instances",
            Self::DescribeStackDrift => "describe-stack-drift",
        }
    }

    /// Check if this operation is read-only (doesn't modify AWS resources)
    pub fn is_read_only(&self) -> bool {
        matches!(self, 
            Self::DescribeStack | 
            Self::EstimateCost | 
            Self::ListStacks | 
            Self::GetStackTemplate | 
            Self::GetStackInstances | 
            Self::DescribeStackDrift
        )
    }
}

impl std::fmt::Display for CfnOperation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

/// Command metadata shown at start of create/update operations
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CommandMetadata {
    pub iidy_environment: String,
    pub region: String,
    pub profile: Option<String>,
    pub cli_arguments: HashMap<String, String>,
    pub iam_service_role: Option<String>,
    pub current_iam_principal: String,
    pub iidy_version: String,
    pub primary_token: TokenInfo,
    pub derived_tokens: Vec<TokenInfo>,
}

/// Core AWS CloudFormation stack event (matches AWS SDK structure)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackEvent {
    pub event_id: String,
    pub stack_id: String,
    pub stack_name: String,
    pub logical_resource_id: String,
    pub physical_resource_id: Option<String>,
    pub resource_type: String,
    pub timestamp: Option<DateTime<Utc>>,
    pub resource_status: String,
    pub resource_status_reason: Option<String>,
    pub resource_properties: Option<String>,
    pub client_request_token: Option<String>,
}

/// Stack event with timing information for display
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackEventWithTiming {
    pub event: StackEvent,
    pub duration_seconds: Option<u64>,
}

/// Truncation information for event lists
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TruncationInfo {
    pub shown: usize,
    pub total: usize,
}

/// Stack events display information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackEventsDisplay {
    pub title: String, // "Previous Stack Events (max 10):" or "Live Stack Events (2s poll):"
    pub events: Vec<StackEventWithTiming>,
    pub max_events: Option<usize>, // Maximum events to display (renderer will sort and limit)
    pub truncated: Option<TruncationInfo>,
}

impl StackEventsDisplay {
    /// Sort events by timestamp and apply max_events limit (newest events last)
    /// Returns (sorted_and_limited_events, truncation_info)
    pub fn get_sorted_limited_events(&self) -> (Vec<StackEventWithTiming>, Option<TruncationInfo>) {
        if self.events.is_empty() {
            return (vec![], None);
        }
        
        // Sort events by timestamp (oldest first, so newest events are shown last)
        let mut sorted_events = self.events.clone();
        sorted_events.sort_by(|a, b| {
            let time_a = a.event.timestamp.map(|t| t.timestamp()).unwrap_or(0);
            let time_b = b.event.timestamp.map(|t| t.timestamp()).unwrap_or(0);
            time_a.cmp(&time_b)
        });
        
        // Apply event limit if specified (keep most recent events)
        let total_events = sorted_events.len();
        if let Some(max_events) = self.max_events {
            if sorted_events.len() > max_events {
                // Take the most recent events (end of sorted list)
                let start_idx = sorted_events.len() - max_events;
                let limited = sorted_events.drain(start_idx..).collect::<Vec<_>>();
                let truncation = Some(TruncationInfo {
                    shown: max_events,
                    total: total_events,
                });
                (limited, truncation)
            } else {
                (sorted_events, None)
            }
        } else {
            (sorted_events, None)
        }
    }
}

/// Stack definition details (from summarizeStackDefinition)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackDefinition {
    pub name: String,
    pub stackset_name: Option<String>, // If StackSet
    pub description: Option<String>,
    pub status: String,
    pub capabilities: Vec<String>,
    pub service_role: Option<String>,
    pub tags: HashMap<String, String>,
    pub parameters: HashMap<String, String>,
    pub disable_rollback: bool,
    pub termination_protection: bool,
    pub creation_time: Option<DateTime<Utc>>,
    pub last_updated_time: Option<DateTime<Utc>>,
    pub timeout_in_minutes: Option<i32>,
    pub notification_arns: Vec<String>,
    pub stack_policy: Option<String>,
    pub arn: String,
    pub console_url: String,
    pub region: String,
}

/// Stack resource information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackResourceInfo {
    pub logical_resource_id: String,
    pub physical_resource_id: Option<String>,
    pub resource_type: String,
    pub resource_status: String,
    pub resource_status_reason: Option<String>,
    pub last_updated_timestamp: Option<DateTime<Utc>>,
}

/// Stack output information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackOutputInfo {
    pub output_key: String,
    pub output_value: String,
    pub description: Option<String>,
    pub export_name: Option<String>,
}

/// Stack export information with import details
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackExportInfo {
    pub name: String,
    pub value: String,
    pub exporting_stack_id: String,
    pub importing_stacks: Vec<String>,
}

/// Current stack status information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackStatusInfo {
    pub status: String,
    pub status_reason: Option<String>,
    pub timestamp: Option<DateTime<Utc>>,
}

/// Changeset information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChangeSetInfo {
    pub change_set_name: String,
    pub change_set_id: String,
    pub stack_id: String,
    pub stack_name: String,
    pub description: Option<String>,
    pub status: String,
    pub status_reason: Option<String>,
    pub creation_time: Option<DateTime<Utc>>,
    pub execution_status: Option<String>,
    pub changes: Vec<ChangeInfo>,
}

/// Individual change within a changeset
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChangeInfo {
    pub action: String, // Add, Modify, Remove
    pub logical_resource_id: String,
    pub resource_type: String,
    pub replacement: Option<String>, // True, False, Conditional
    pub details: Vec<ChangeDetail>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChangeDetail {
    pub target: String,
    pub evaluation: Option<String>,
    pub change_source: Option<String>,
    pub causing_entity: Option<String>,
}

/// Stack contents display information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackContents {
    pub resources: Vec<StackResourceInfo>,
    pub outputs: Vec<StackOutputInfo>,
    pub exports: Vec<StackExportInfo>,
    pub current_status: StackStatusInfo,
    pub pending_changesets: Vec<ChangeSetInfo>,
}

/// Status update information for live operations
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StatusUpdate {
    pub message: String,
    pub timestamp: DateTime<Utc>,
    pub level: StatusLevel,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum StatusLevel {
    Info,
    Warning,
    Error,
    Success,
}

/// Command execution result
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CommandResult {
    pub success: bool,
    pub elapsed_seconds: u64,
    pub message: Option<String>,
    pub exit_code: i32,
}

/// Final command summary result (matches iidy-js showFinalComandSummary)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct FinalCommandSummary {
    pub result: CommandSummaryResult,
    pub elapsed_seconds: i64,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum CommandSummaryResult {
    Success,
    Failure,
}

/// Available columns for stack list display
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum StackListColumn {
    Name,
    Status, 
    Time,
    Tags,
    StatusReason,
    TerminationProtection,
    Environment,
}

impl StackListColumn {
    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "name" => Some(Self::Name),
            "status" => Some(Self::Status),
            "time" | "creation_time" | "last_updated_time" => Some(Self::Time),
            "tags" => Some(Self::Tags),
            "status_reason" | "reason" => Some(Self::StatusReason),
            "termination_protection" | "protection" => Some(Self::TerminationProtection),
            "environment" | "env" => Some(Self::Environment),
            _ => None,
        }
    }
    
    pub fn default_columns() -> Vec<Self> {
        vec![Self::Time, Self::Status, Self::Name, Self::Tags]
    }
}

/// Stack list display information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackListDisplay {
    pub stacks: Vec<StackListEntry>,
    pub show_tags: bool,
    pub filters_applied: Vec<String>,
    pub columns: Vec<StackListColumn>,
    pub query_mode: bool, // True for raw JSON array output (--query flag)
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackListEntry {
    pub stack_name: String,
    pub stack_status: String,
    pub creation_time: Option<DateTime<Utc>>,
    pub last_updated_time: Option<DateTime<Utc>>,
    pub tags: HashMap<String, String>,
    pub status_reason: Option<String>,
    pub termination_protection: bool,
    pub environment_type: Option<String>, // production, integration, development
}

/// Changeset creation result
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChangeSetCreationResult {
    pub changeset_name: String,
    pub stack_name: String,
    pub changeset_type: String, // CREATE or UPDATE
    pub status: String,
    pub console_url: String,
    pub has_changes: bool,
    pub pending_changesets: Vec<ChangeSetInfo>,
    pub next_steps: Vec<String>,
}

/// Error information for display
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ErrorInfo {
    pub error_type: String,
    pub message: String,
    pub details: Option<String>,
    pub timestamp: DateTime<Utc>,
    pub suggestions: Vec<String>,
}

/// Operation completion information for live operations
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OperationCompleteInfo {
    pub elapsed_seconds: i64,
    pub operation_start_time: DateTime<Utc>,
    pub skip_remaining_sections: bool, // For DELETE_COMPLETE or other cases where we don't want stack contents
}

/// Inactivity timeout information for live operations
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct InactivityTimeoutInfo {
    pub timeout_seconds: u64,
    pub elapsed_seconds: i64,
    pub operation_start_time: DateTime<Utc>,
}


/// Stack drift information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackDrift {
    pub drifted_resources: Vec<DriftedResource>,
}

/// Individual drifted resource
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DriftedResource {
    pub logical_resource_id: String,
    pub physical_resource_id: String,
    pub resource_type: String,
    pub drift_status: String,
    pub property_differences: Vec<PropertyDifference>,
}

/// Property difference for drift detection
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PropertyDifference {
    pub property_path: String,
    pub expected_value: Option<String>,
    pub actual_value: Option<String>,
    pub difference_type: Option<String>,
}


/// Main output data enum for the manager
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum OutputData {
    CommandMetadata(CommandMetadata),
    StackDefinition(StackDefinition, bool), // bool = show_times flag
    StackEvents(StackEventsDisplay),
    StackContents(StackContents),
    StatusUpdate(StatusUpdate),
    CommandResult(CommandResult),
    FinalCommandSummary(FinalCommandSummary),
    StackList(StackListDisplay),
    ChangeSetResult(ChangeSetCreationResult),
    StackDrift(StackDrift),
    Error(ErrorInfo),
    TokenInfo(TokenInfo),
    NewStackEvents(Vec<StackEventWithTiming>), // Batch of new events for live watch (no title/header)
    OperationComplete(OperationCompleteInfo), // Signal that live operation finished successfully
    InactivityTimeout(InactivityTimeoutInfo), // Signal that operation timed out due to inactivity
}

impl OutputData {
    /// Get a short description of the data type for logging
    pub fn data_type(&self) -> &'static str {
        match self {
            OutputData::CommandMetadata(_) => "command_metadata",
            OutputData::StackDefinition(_, _) => "stack_definition",
            OutputData::StackEvents(_) => "stack_events",
            OutputData::StackContents(_) => "stack_contents",
            OutputData::StatusUpdate(_) => "status_update",
            OutputData::CommandResult(_) => "command_result",
            OutputData::FinalCommandSummary(_) => "final_command_summary",
            OutputData::StackList(_) => "stack_list",
            OutputData::ChangeSetResult(_) => "changeset_result",
            OutputData::StackDrift(_) => "stack_drift",
            OutputData::Error(_) => "error",
            OutputData::TokenInfo(_) => "token_info",
            OutputData::NewStackEvents(_) => "new_stack_events",
            OutputData::OperationComplete(_) => "operation_complete",
            OutputData::InactivityTimeout(_) => "inactivity_timeout",
        }
    }
    
}

