//! Core data structures for data-driven output architecture
//!
//! These structures capture exactly what iidy-js displays, separated from
//! presentation logic to enable multiple output modes.

use std::collections::HashMap;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Token information from the existing token management system
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TokenInfo {
    pub value: String,
    pub source: TokenSource,
    pub operation_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum TokenSource {
    UserProvided,
    AutoGenerated,
    Derived { from: String, step: String },
}

/// Command metadata shown at start of create/update operations
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CommandMetadata {
    pub cfn_operation: String,
    pub iidy_environment: String,
    pub region: String,
    pub profile: Option<String>,
    pub cli_arguments: HashMap<String, String>,
    pub iam_service_role: Option<String>,
    pub current_iam_principal: String,
    pub iidy_version: String,
    pub primary_token: TokenInfo,
    pub derived_tokens: Vec<TokenInfo>,
}

/// Core AWS CloudFormation stack event (matches AWS SDK structure)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackEvent {
    pub event_id: String,
    pub stack_id: String,
    pub stack_name: String,
    pub logical_resource_id: String,
    pub physical_resource_id: Option<String>,
    pub resource_type: String,
    pub timestamp: Option<DateTime<Utc>>,
    pub resource_status: String,
    pub resource_status_reason: Option<String>,
    pub resource_properties: Option<String>,
    pub client_request_token: Option<String>,
}

/// Stack event with timing information for display
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackEventWithTiming {
    pub event: StackEvent,
    pub duration_seconds: Option<u64>,
}

/// Truncation information for event lists
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TruncationInfo {
    pub shown: usize,
    pub total: usize,
}

/// Stack events display information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackEventsDisplay {
    pub title: String, // "Previous Stack Events (max 10):" or "Live Stack Events (2s poll):"
    pub events: Vec<StackEventWithTiming>,
    pub max_events: Option<usize>, // Maximum events to display (renderer will sort and limit)
    pub truncated: Option<TruncationInfo>,
}

impl StackEventsDisplay {
    /// Sort events by timestamp and apply max_events limit (newest events last)
    /// Returns (sorted_and_limited_events, truncation_info)
    pub fn get_sorted_limited_events(&self) -> (Vec<StackEventWithTiming>, Option<TruncationInfo>) {
        if self.events.is_empty() {
            return (vec![], None);
        }
        
        // Sort events by timestamp (oldest first, so newest events are shown last)
        let mut sorted_events = self.events.clone();
        sorted_events.sort_by(|a, b| {
            let time_a = a.event.timestamp.map(|t| t.timestamp()).unwrap_or(0);
            let time_b = b.event.timestamp.map(|t| t.timestamp()).unwrap_or(0);
            time_a.cmp(&time_b)
        });
        
        // Apply event limit if specified (keep most recent events)
        let total_events = sorted_events.len();
        if let Some(max_events) = self.max_events {
            if sorted_events.len() > max_events {
                // Take the most recent events (end of sorted list)
                let start_idx = sorted_events.len() - max_events;
                let limited = sorted_events.drain(start_idx..).collect::<Vec<_>>();
                let truncation = Some(TruncationInfo {
                    shown: max_events,
                    total: total_events,
                });
                (limited, truncation)
            } else {
                (sorted_events, None)
            }
        } else {
            (sorted_events, None)
        }
    }
}

/// Stack definition details (from summarizeStackDefinition)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackDefinition {
    pub name: String,
    pub stackset_name: Option<String>, // If StackSet
    pub description: Option<String>,
    pub status: String,
    pub capabilities: Vec<String>,
    pub service_role: Option<String>,
    pub tags: HashMap<String, String>,
    pub parameters: HashMap<String, String>,
    pub disable_rollback: bool,
    pub termination_protection: bool,
    pub creation_time: Option<DateTime<Utc>>,
    pub last_updated_time: Option<DateTime<Utc>>,
    pub timeout_in_minutes: Option<i32>,
    pub notification_arns: Vec<String>,
    pub stack_policy: Option<String>,
    pub arn: String,
    pub console_url: String,
    pub region: String,
}

/// Stack resource information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackResourceInfo {
    pub logical_resource_id: String,
    pub physical_resource_id: Option<String>,
    pub resource_type: String,
    pub resource_status: String,
    pub resource_status_reason: Option<String>,
    pub last_updated_timestamp: Option<DateTime<Utc>>,
}

/// Stack output information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackOutputInfo {
    pub output_key: String,
    pub output_value: String,
    pub description: Option<String>,
    pub export_name: Option<String>,
}

/// Stack export information with import details
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackExportInfo {
    pub name: String,
    pub value: String,
    pub exporting_stack_id: String,
    pub importing_stacks: Vec<String>,
}

/// Current stack status information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackStatusInfo {
    pub status: String,
    pub status_reason: Option<String>,
    pub timestamp: Option<DateTime<Utc>>,
}

/// Changeset information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChangeSetInfo {
    pub change_set_name: String,
    pub change_set_id: String,
    pub stack_id: String,
    pub stack_name: String,
    pub description: Option<String>,
    pub status: String,
    pub status_reason: Option<String>,
    pub creation_time: Option<DateTime<Utc>>,
    pub execution_status: Option<String>,
    pub changes: Vec<ChangeInfo>,
}

/// Individual change within a changeset
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChangeInfo {
    pub action: String, // Add, Modify, Remove
    pub logical_resource_id: String,
    pub resource_type: String,
    pub replacement: Option<String>, // True, False, Conditional
    pub details: Vec<ChangeDetail>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChangeDetail {
    pub target: String,
    pub evaluation: Option<String>,
    pub change_source: Option<String>,
    pub causing_entity: Option<String>,
}

/// Stack contents display information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackContents {
    pub resources: Vec<StackResourceInfo>,
    pub outputs: Vec<StackOutputInfo>,
    pub exports: Vec<StackExportInfo>,
    pub current_status: StackStatusInfo,
    pub pending_changesets: Vec<ChangeSetInfo>,
}

/// Status update information for live operations
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StatusUpdate {
    pub message: String,
    pub timestamp: DateTime<Utc>,
    pub level: StatusLevel,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum StatusLevel {
    Info,
    Warning,
    Error,
    Success,
}

/// Command execution result
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CommandResult {
    pub success: bool,
    pub elapsed_seconds: u64,
    pub message: Option<String>,
    pub exit_code: i32,
}

/// Stack list display information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackListDisplay {
    pub stacks: Vec<StackListEntry>,
    pub show_tags: bool,
    pub filters_applied: Vec<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackListEntry {
    pub stack_name: String,
    pub stack_status: String,
    pub creation_time: Option<DateTime<Utc>>,
    pub last_updated_time: Option<DateTime<Utc>>,
    pub tags: HashMap<String, String>,
    pub status_reason: Option<String>,
    pub termination_protection: bool,
    pub environment_type: Option<String>, // production, integration, development
}

/// Changeset creation result
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ChangeSetCreationResult {
    pub changeset_name: String,
    pub stack_name: String,
    pub changeset_type: String, // CREATE or UPDATE
    pub status: String,
    pub console_url: String,
    pub has_changes: bool,
    pub pending_changesets: Vec<ChangeSetInfo>,
    pub next_steps: Vec<String>,
}

/// Error information for display
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ErrorInfo {
    pub error_type: String,
    pub message: String,
    pub details: Option<String>,
    pub timestamp: DateTime<Utc>,
    pub suggestions: Vec<String>,
}


/// Stack drift information
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct StackDrift {
    pub drifted_resources: Vec<DriftedResource>,
}

/// Individual drifted resource
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DriftedResource {
    pub logical_resource_id: String,
    pub physical_resource_id: String,
    pub resource_type: String,
    pub drift_status: String,
    pub property_differences: Vec<PropertyDifference>,
}

/// Property difference for drift detection
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PropertyDifference {
    pub property_path: String,
    pub expected_value: Option<String>,
    pub actual_value: Option<String>,
    pub difference_type: Option<String>,
}

/// Main output data enum for the manager
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum OutputData {
    CommandMetadata(CommandMetadata),
    StackDefinition(StackDefinition, bool), // bool = show_times flag
    StackEvents(StackEventsDisplay),
    StackContents(StackContents),
    StatusUpdate(StatusUpdate),
    CommandResult(CommandResult),
    StackList(StackListDisplay),
    ChangeSetResult(ChangeSetCreationResult),
    StackDrift(StackDrift),
    Error(ErrorInfo),
    TokenInfo(TokenInfo),
}

impl OutputData {
    /// Get a short description of the data type for logging
    pub fn data_type(&self) -> &'static str {
        match self {
            OutputData::CommandMetadata(_) => "command_metadata",
            OutputData::StackDefinition(_, _) => "stack_definition",
            OutputData::StackEvents(_) => "stack_events",
            OutputData::StackContents(_) => "stack_contents",
            OutputData::StatusUpdate(_) => "status_update",
            OutputData::CommandResult(_) => "command_result",
            OutputData::StackList(_) => "stack_list",
            OutputData::ChangeSetResult(_) => "changeset_result",
            OutputData::StackDrift(_) => "stack_drift",
            OutputData::Error(_) => "error",
            OutputData::TokenInfo(_) => "token_info",
        }
    }
}