//! Demo program for the data-driven output architecture
//!
//! This demonstrates the working PlainTextRenderer with fixture data
//! and shows how the system works end-to-end.

use crate::output::*;
use anyhow::Result;

/// Run a demo of the output system with fixture data
pub async fn run_output_demo() -> Result<()> {
    println!("🚀 Data-Driven Output Architecture Demo");
    println!("=======================================\n");
    
    // Try to load fixture data (will fall back to sample data if fixture file not found)
    let output_data = match FixtureLoader::new().load_happy_path_data() {
        Ok(data) => {
            println!("✅ Loaded fixture data from tests/fixtures/create-stack-happy-path.yaml");
            data
        }
        Err(e) => {
            println!("⚠️  Could not load fixture data ({}), using sample data", e);
            sample_output_data()
        }
    };
    
    println!("📊 Generated {} output data items\n", output_data.len());
    
    // Create PlainTextRenderer via OutputManager
    let options = OutputOptions {
        color_choice: crate::cli::ColorChoice::Never,
        theme: crate::cli::Theme::Auto,
        terminal_width: Some(120),
        buffer_limit: 100,
    };
    
    let mut output_manager = DynamicOutputManager::new(OutputMode::Plain, options).await?;
    
    println!("🖨️  Rendering output in Plain mode:");
    println!("═══════════════════════════════════\n");
    
    // Render all data items
    for (i, data) in output_data.iter().enumerate() {
        println!("--- Data item {} ({}) ---", i + 1, data.data_type());
        output_manager.render(data.clone()).await?;
        println!();
    }
    
    println!("✅ Demo completed successfully!");
    println!("   - {} data structures rendered", output_data.len());
    println!("   - PlainTextRenderer working correctly");
    println!("   - DynamicOutputManager operational");
    println!("   - Fixture system (fallback to samples) functional");
    
    Ok(())
}

/// Generate sample output data if fixtures aren't available
fn sample_output_data() -> Vec<OutputData> {
    use std::collections::HashMap;
    use chrono::{Utc, TimeZone};
    
    let mut cli_arguments = HashMap::new();
    cli_arguments.insert("region".to_string(), "us-east-1".to_string());
    cli_arguments.insert("profile".to_string(), "development".to_string());
    cli_arguments.insert("argsfile".to_string(), "stack-args.yaml".to_string());

    vec![
        OutputData::CommandMetadata(CommandMetadata {
            cfn_operation: "create-stack".to_string(),
            iidy_environment: "development".to_string(),
            region: "us-east-1".to_string(),
            profile: Some("dev-profile".to_string()),
            cli_arguments,
            iam_service_role: Some("arn:aws:iam::123456789012:role/CloudFormationRole".to_string()),
            current_iam_principal: "arn:aws:iam::123456789012:user/developer".to_string(),
            iidy_version: "0.1.0".to_string(),
            primary_token: TokenInfo {
                value: "sample-token-12345678-abcd-efgh-ijkl-123456789012".to_string(),
                source: TokenSource::AutoGenerated,
                operation_id: "op-001".to_string(),
            },
            derived_tokens: vec![],
        }),
        
        OutputData::StatusUpdate(StatusUpdate {
            message: "Stack operation in progress - 2 resources remaining".to_string(),
            timestamp: Utc::now(),
            level: StatusLevel::Info,
        }),
        
        OutputData::CommandResult(CommandResult {
            success: true,
            elapsed_seconds: 347,
            message: Some("Stack creation completed successfully".to_string()),
            exit_code: 0,
        }),
    ]
}