//! Test data and mocks for output renderer development and testing
//!
//! This module provides realistic sample data structures that match
//! actual AWS CloudFormation responses for testing renderers.

use crate::output::data::*;
use chrono::{DateTime, Utc, TimeZone};
use std::collections::HashMap;

/// Create sample command metadata for testing
pub fn sample_command_metadata() -> CommandMetadata {
    let mut cli_arguments = HashMap::new();
    cli_arguments.insert("region".to_string(), "us-east-1".to_string());
    cli_arguments.insert("profile".to_string(), "development".to_string());
    cli_arguments.insert("argsfile".to_string(), "stack-args.yaml".to_string());

    CommandMetadata {
        cfn_operation: CfnOperation::CreateStack,
        iidy_environment: "development".to_string(),
        region: "us-east-1".to_string(),
        profile: Some("dev-profile".to_string()),
        cli_arguments,
        iam_service_role: Some("arn:aws:iam::123456789012:role/CloudFormationRole".to_string()),
        current_iam_principal: "arn:aws:iam::123456789012:user/developer".to_string(),
        iidy_version: "0.1.0".to_string(),
        primary_token: TokenInfo {
            value: "abc123-def456-ghi789".to_string(),
            source: TokenSource::AutoGenerated,
            operation_id: "op-001".to_string(),
        },
        derived_tokens: vec![
            TokenInfo {
                value: "derived-001".to_string(),
                source: TokenSource::Derived {
                    from: "abc123-def456-ghi789".to_string(),
                    step: "changeset-creation".to_string(),
                },
                operation_id: "op-001-cs".to_string(),
            },
        ],
    }
}

/// Create sample stack definition for testing
pub fn sample_stack_definition() -> StackDefinition {
    let mut tags = HashMap::new();
    tags.insert("environment".to_string(), "development".to_string());
    tags.insert("project".to_string(), "iidy-test".to_string());
    tags.insert("owner".to_string(), "development-team".to_string());

    let mut parameters = HashMap::new();
    parameters.insert("InstanceType".to_string(), "t3.micro".to_string());
    parameters.insert("Environment".to_string(), "dev".to_string());

    StackDefinition {
        name: "iidy-test-stack".to_string(),
        stackset_name: None,
        description: Some("Test stack for iidy development".to_string()),
        status: "CREATE_COMPLETE".to_string(),
        capabilities: vec!["CAPABILITY_IAM".to_string()],
        service_role: Some("arn:aws:iam::123456789012:role/CloudFormationRole".to_string()),
        tags,
        parameters,
        disable_rollback: false,
        termination_protection: false,
        creation_time: Some(Utc.with_ymd_and_hms(2025, 6, 17, 10, 30, 0).unwrap()),
        last_updated_time: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 15, 30).unwrap()),
        timeout_in_minutes: Some(10),
        notification_arns: vec![],
        stack_policy: Some(r#"{"Statement":[{"Effect":"Allow","Principal":"*","Action":"Update:*","Resource":"*"}]}"#.to_string()),
        arn: "arn:aws:cloudformation:us-east-1:123456789012:stack/iidy-test-stack/12345678-1234-1234-1234-123456789012".to_string(),
        console_url: "https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A123456789012%3Astack%2Fiidy-test-stack%2F12345678-1234-1234-1234-123456789012".to_string(),
        region: "us-east-1".to_string(),
    }
}

/// Create sample stack events for testing
pub fn sample_stack_events() -> StackEventsDisplay {
    let events = vec![
        StackEventWithTiming {
            event: StackEvent {
                event_id: "event-001".to_string(),
                stack_id: "arn:aws:cloudformation:us-east-1:123456789012:stack/iidy-test-stack/12345678-1234-1234-1234-123456789012".to_string(),
                stack_name: "iidy-test-stack".to_string(),
                logical_resource_id: "iidy-test-stack".to_string(),
                physical_resource_id: Some("arn:aws:cloudformation:us-east-1:123456789012:stack/iidy-test-stack/12345678-1234-1234-1234-123456789012".to_string()),
                resource_type: "AWS::CloudFormation::Stack".to_string(),
                timestamp: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 15, 30).unwrap()),
                resource_status: "CREATE_COMPLETE".to_string(),
                resource_status_reason: Some("Stack creation completed successfully".to_string()),
                resource_properties: None,
                client_request_token: Some("abc123-def456-ghi789".to_string()),
            },
            duration_seconds: Some(300),
        },
        StackEventWithTiming {
            event: StackEvent {
                event_id: "event-002".to_string(),
                stack_id: "arn:aws:cloudformation:us-east-1:123456789012:stack/iidy-test-stack/12345678-1234-1234-1234-123456789012".to_string(),
                stack_name: "iidy-test-stack".to_string(),
                logical_resource_id: "MyBucket".to_string(),
                physical_resource_id: Some("iidy-test-stack-mybucket-1a2b3c4d5e6f".to_string()),
                resource_type: "AWS::S3::Bucket".to_string(),
                timestamp: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 15, 0).unwrap()),
                resource_status: "CREATE_COMPLETE".to_string(),
                resource_status_reason: None,
                resource_properties: None,
                client_request_token: Some("abc123-def456-ghi789".to_string()),
            },
            duration_seconds: Some(45),
        },
        StackEventWithTiming {
            event: StackEvent {
                event_id: "event-003".to_string(),
                stack_id: "arn:aws:cloudformation:us-east-1:123456789012:stack/iidy-test-stack/12345678-1234-1234-1234-123456789012".to_string(),
                stack_name: "iidy-test-stack".to_string(),
                logical_resource_id: "MyBucket".to_string(),
                physical_resource_id: Some("iidy-test-stack-mybucket-1a2b3c4d5e6f".to_string()),
                resource_type: "AWS::S3::Bucket".to_string(),
                timestamp: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 14, 15).unwrap()),
                resource_status: "CREATE_IN_PROGRESS".to_string(),
                resource_status_reason: Some("Resource creation initiated".to_string()),
                resource_properties: None,
                client_request_token: Some("abc123-def456-ghi789".to_string()),
            },
            duration_seconds: None,
        },
        StackEventWithTiming {
            event: StackEvent {
                event_id: "event-004".to_string(),
                stack_id: "arn:aws:cloudformation:us-east-1:123456789012:stack/iidy-test-stack/12345678-1234-1234-1234-123456789012".to_string(),
                stack_name: "iidy-test-stack".to_string(),
                logical_resource_id: "MySecurityGroup".to_string(),
                physical_resource_id: Some("sg-0123456789abcdef0".to_string()),
                resource_type: "AWS::EC2::SecurityGroup".to_string(),
                timestamp: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 13, 45).unwrap()),
                resource_status: "CREATE_COMPLETE".to_string(),
                resource_status_reason: None,
                resource_properties: None,
                client_request_token: Some("abc123-def456-ghi789".to_string()),
            },
            duration_seconds: Some(20),
        },
    ];

    StackEventsDisplay {
        title: "Previous Stack Events (max 10):".to_string(),
        events,
        truncated: Some(TruncationInfo {
            shown: 4,
            total: 8,
        }),
    }
}

/// Create sample stack contents for testing
pub fn sample_stack_contents() -> StackContents {
    let resources = vec![
        StackResourceInfo {
            logical_resource_id: "MyBucket".to_string(),
            physical_resource_id: Some("iidy-test-stack-mybucket-1a2b3c4d5e6f".to_string()),
            resource_type: "AWS::S3::Bucket".to_string(),
            resource_status: "CREATE_COMPLETE".to_string(),
            resource_status_reason: None,
            last_updated_timestamp: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 15, 0).unwrap()),
        },
        StackResourceInfo {
            logical_resource_id: "MySecurityGroup".to_string(),
            physical_resource_id: Some("sg-0123456789abcdef0".to_string()),
            resource_type: "AWS::EC2::SecurityGroup".to_string(),
            resource_status: "CREATE_COMPLETE".to_string(),
            resource_status_reason: None,
            last_updated_timestamp: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 13, 45).unwrap()),
        },
        StackResourceInfo {
            logical_resource_id: "MyInstance".to_string(),
            physical_resource_id: Some("i-0123456789abcdef0".to_string()),
            resource_type: "AWS::EC2::Instance".to_string(),
            resource_status: "CREATE_COMPLETE".to_string(),
            resource_status_reason: None,
            last_updated_timestamp: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 14, 30).unwrap()),
        },
    ];

    let outputs = vec![
        StackOutputInfo {
            output_key: "BucketName".to_string(),
            output_value: "iidy-test-stack-mybucket-1a2b3c4d5e6f".to_string(),
            description: Some("The name of the S3 bucket".to_string()),
            export_name: Some("iidy-test-stack-bucket-name".to_string()),
        },
        StackOutputInfo {
            output_key: "InstanceId".to_string(),
            output_value: "i-0123456789abcdef0".to_string(),
            description: Some("The ID of the EC2 instance".to_string()),
            export_name: None,
        },
    ];

    let exports = vec![
        StackExportInfo {
            name: "iidy-test-stack-bucket-name".to_string(),
            value: "iidy-test-stack-mybucket-1a2b3c4d5e6f".to_string(),
            exporting_stack_id: "arn:aws:cloudformation:us-east-1:123456789012:stack/iidy-test-stack/12345678-1234-1234-1234-123456789012".to_string(),
            importing_stacks: vec![
                "arn:aws:cloudformation:us-east-1:123456789012:stack/dependent-stack-1/87654321-4321-4321-4321-210987654321".to_string(),
                "arn:aws:cloudformation:us-east-1:123456789012:stack/dependent-stack-2/11111111-2222-3333-4444-555555555555".to_string(),
            ],
        },
    ];

    let current_status = StackStatusInfo {
        status: "CREATE_COMPLETE".to_string(),
        status_reason: Some("Stack creation completed successfully".to_string()),
        timestamp: Some(Utc.with_ymd_and_hms(2025, 6, 17, 11, 15, 30).unwrap()),
    };

    let pending_changesets = vec![
        ChangeSetInfo {
            change_set_name: "update-instance-type".to_string(),
            change_set_id: "arn:aws:cloudformation:us-east-1:123456789012:changeSet/update-instance-type/12345678-1234-1234-1234-123456789012".to_string(),
            stack_id: "arn:aws:cloudformation:us-east-1:123456789012:stack/iidy-test-stack/12345678-1234-1234-1234-123456789012".to_string(),
            stack_name: "iidy-test-stack".to_string(),
            description: Some("Update EC2 instance type from t3.micro to t3.small".to_string()),
            status: "CREATE_COMPLETE".to_string(),
            status_reason: None,
            creation_time: Some(Utc.with_ymd_and_hms(2025, 6, 17, 12, 0, 0).unwrap()),
            execution_status: Some("AVAILABLE".to_string()),
            changes: vec![
                ChangeInfo {
                    action: "Modify".to_string(),
                    logical_resource_id: "MyInstance".to_string(),
                    resource_type: "AWS::EC2::Instance".to_string(),
                    replacement: Some("False".to_string()),
                    details: vec![
                        ChangeDetail {
                            target: "Properties.InstanceType".to_string(),
                            evaluation: Some("Static".to_string()),
                            change_source: Some("DirectModification".to_string()),
                            causing_entity: None,
                        },
                    ],
                },
            ],
        },
    ];

    StackContents {
        resources,
        outputs,
        exports,
        current_status,
        pending_changesets,
    }
}

/// Create sample status update for testing
pub fn sample_status_update() -> StatusUpdate {
    StatusUpdate {
        message: "Stack operation in progress - 2 resources remaining".to_string(),
        timestamp: Utc.with_ymd_and_hms(2025, 6, 17, 11, 16, 0).unwrap(),
        level: StatusLevel::Info,
    }
}

/// Create sample command result for testing
pub fn sample_command_result(success: bool) -> CommandResult {
    CommandResult {
        success,
        elapsed_seconds: 347,
        message: if success {
            Some("Stack creation completed successfully".to_string())
        } else {
            Some("Stack creation failed due to resource limit exceeded".to_string())
        },
        exit_code: if success { 0 } else { 1 },
    }
}

/// Create sample stack list for testing
pub fn sample_stack_list() -> StackListDisplay {
    let mut prod_tags = HashMap::new();
    prod_tags.insert("environment".to_string(), "production".to_string());
    prod_tags.insert("lifetime".to_string(), "protected".to_string());

    let mut dev_tags = HashMap::new();
    dev_tags.insert("environment".to_string(), "development".to_string());
    dev_tags.insert("lifetime".to_string(), "short".to_string());

    let stacks = vec![
        StackListEntry {
            stack_name: "production-api-stack".to_string(),
            stack_status: "UPDATE_COMPLETE".to_string(),
            creation_time: Some(Utc.with_ymd_and_hms(2025, 6, 10, 9, 0, 0).unwrap()),
            last_updated_time: Some(Utc.with_ymd_and_hms(2025, 6, 16, 14, 30, 0).unwrap()),
            tags: prod_tags,
            status_reason: None,
            termination_protection: true,
            environment_type: Some("production".to_string()),
        },
        StackListEntry {
            stack_name: "development-test-stack".to_string(),
            stack_status: "CREATE_COMPLETE".to_string(),
            creation_time: Some(Utc.with_ymd_and_hms(2025, 6, 17, 10, 30, 0).unwrap()),
            last_updated_time: None,
            tags: dev_tags,
            status_reason: None,
            termination_protection: false,
            environment_type: Some("development".to_string()),
        },
        StackListEntry {
            stack_name: "failed-experiment-stack".to_string(),
            stack_status: "CREATE_FAILED".to_string(),
            creation_time: Some(Utc.with_ymd_and_hms(2025, 6, 17, 8, 0, 0).unwrap()),
            last_updated_time: None,
            tags: HashMap::new(),
            status_reason: Some("Resource limit exceeded: Cannot create more than 5 security groups per VPC".to_string()),
            termination_protection: false,
            environment_type: None,
        },
    ];

    StackListDisplay {
        stacks,
        show_tags: true,
        filters_applied: vec![
            "tag-filter: environment=*".to_string(),
        ],
    }
}

/// Create sample changeset result for testing
pub fn sample_changeset_result() -> ChangeSetCreationResult {
    ChangeSetCreationResult {
        changeset_name: "update-instance-type".to_string(),
        stack_name: "iidy-test-stack".to_string(),
        changeset_type: "UPDATE".to_string(),
        status: "CREATE_COMPLETE".to_string(),
        console_url: "https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/changeset/detail?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A123456789012%3Astack%2Fiidy-test-stack%2F12345678-1234-1234-1234-123456789012&changeSetId=update-instance-type".to_string(),
        has_changes: true,
        pending_changesets: vec![],
        next_steps: vec![
            "Review the changeset in the AWS Console".to_string(),
            "Execute the changeset using: iidy exec-changeset stack-args.yaml update-instance-type".to_string(),
        ],
    }
}

/// Create sample error info for testing
pub fn sample_error_info() -> ErrorInfo {
    ErrorInfo {
        error_type: "ValidationError".to_string(),
        message: "Template validation failed: Resource 'MyBucket' property 'BucketName' is invalid".to_string(),
        details: Some("The bucket name 'MyBucket' does not conform to S3 naming conventions. Bucket names must be lowercase and contain only letters, numbers, and hyphens.".to_string()),
        timestamp: Utc.with_ymd_and_hms(2025, 6, 17, 11, 30, 0).unwrap(),
        suggestions: vec![
            "Update the BucketName property to use lowercase letters".to_string(),
            "Consider using the !Ref function to generate a unique bucket name".to_string(),
            "Review the S3 bucket naming guidelines in the AWS documentation".to_string(),
        ],
    }
}

/// Create all sample output data variations for comprehensive testing
pub fn all_sample_output_data() -> Vec<OutputData> {
    vec![
        OutputData::CommandMetadata(sample_command_metadata()),
        OutputData::StackDefinition(sample_stack_definition(), true),
        OutputData::StackEvents(sample_stack_events()),
        OutputData::StackContents(sample_stack_contents()),
        OutputData::StatusUpdate(sample_status_update()),
        OutputData::CommandResult(sample_command_result(true)),
        OutputData::CommandResult(sample_command_result(false)),
        OutputData::StackList(sample_stack_list()),
        OutputData::ChangeSetResult(sample_changeset_result()),
        OutputData::Error(sample_error_info()),
    ]
}